import type { PurchasePlanItem } from './types';

export const PURCHASING_PLAN_DATA: PurchasePlanItem[] = [
  {
    "id": "MM-3200",
    "aircraft": "525 CJ1, 525A CJ2, 525B CJ3, 525C CJ4, 560 Citation V, 560 Encore, 560 Encore+, 560 Ultra, Citation X+, Citation X, 560XL-XLS+, 560XL-XLS, 560XL Excel",
    "name": "Robo Mule",
    "partNumber": "MM-3200",
    "manufacturer": "Alberth Air Parts",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 1",
    "unitPrice": "$4,950.00",
    "quantity": "1",
    "totalPrice": "$4,950.00",
    "sourcingLink": "https://alberthaviation.com/products/hydraulic-mule/",
    "requestId": "RQ25-00026.1",
    "status": "Received",
    "notes": "Pending Approval; BJC; Approved; Received 26SEP2025"
  },
  {
    "id": "DCS33-33E",
    "aircraft": "525B CJ3, 525A CJ2, 525C CJ4, 525 CJ1",
    "name": "28 volt power supply",
    "partNumber": "DCS33-33E",
    "manufacturer": "N/A",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 1",
    "unitPrice": "",
    "quantity": "0",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "RQ25-00031.1",
    "status": "Not Needed",
    "notes": "Own Equivilent; Both; Not needed, alternate on hand"
  },
  {
    "id": "K-1288",
    "aircraft": "525C CJ4",
    "name": "cabin pressurization test cart adapter kit",
    "partNumber": "K-1288",
    "manufacturer": "Tronair",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 1",
    "unitPrice": "$1,632.00",
    "quantity": "1",
    "totalPrice": "$1,632.00",
    "sourcingLink": "Proserv Aviation Quote Q18107",
    "requestId": "RQ25-00032.1",
    "status": "Approved",
    "notes": "Pending Approval; Approved"
  },
  {
    "id": "8788005-1",
    "aircraft": "525C CJ4",
    "name": "flap breakout box",
    "partNumber": "8788005-1",
    "manufacturer": "Cessna",
    "reason": "Needed for Repairs",
    "stage": "Stage 1",
    "unitPrice": "$5,140.20",
    "quantity": "1",
    "totalPrice": "$5,140.20",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/8788005-1",
    "requestId": "RQ25-00033.1",
    "status": "Received",
    "notes": "Sourcing; Received 26SEP2025"
  },
  {
    "id": "CJMD128-001",
    "aircraft": "525C CJ4, 525 CJ1, 525A CJ2, 525B CJ3, 560 Encore+, 560 Citation V, 560 Encore, 560 Ultra, 560XL Excel, 560XL-XLS, 560XL-XLS+, Citation X, Citation X+",
    "name": "fuel drain valve removal tool",
    "partNumber": "CJMD128-001",
    "manufacturer": "Cessna",
    "reason": "Needed for Repairs",
    "stage": "Stage 1",
    "unitPrice": "$70.06",
    "quantity": "0",
    "totalPrice": "$0.00",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/CJMD128-001",
    "requestId": "",
    "status": "Approved",
    "notes": "Own Equivilent; Approved"
  },
  {
    "id": "6388012-1 (CJMD828-002)",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "fuel quantity test set",
    "partNumber": "6388012-1 (CJMD828-002)",
    "manufacturer": "Cessna",
    "reason": "Need For Advanced Troubleshooting",
    "stage": "Stage 1",
    "unitPrice": "$6,322.00",
    "quantity": "1",
    "totalPrice": "$6,322.00",
    "sourcingLink": "https://aeroval.com/ref/493202/CJMD828-002/",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing; waiting for vendors"
  },
  {
    "id": "5520151-1_adapter",
    "aircraft": "525C CJ4, 525 CJ1, 525A CJ2, 525B CJ3, 560 Citation V, 560 Encore, 560 Encore+, 560 Ultra, 560XL-XLS, 560XL-XLS+, 560XL Excel",
    "name": "jack pad adapter",
    "partNumber": "5520151-1",
    "manufacturer": "Cessna",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 1",
    "unitPrice": "$142.12",
    "quantity": "0",
    "totalPrice": "$0.00",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/5520151-1",
    "requestId": "",
    "status": "Received",
    "notes": "Own Equivilent; BJC; \"Approved; Zenith has NS with CoC for 70.00\"; Received 26SEP2025"
  },
  {
    "id": "8788001-8",
    "aircraft": "525C CJ4",
    "name": "landing gear simulator test box",
    "partNumber": "8788001-8",
    "manufacturer": "Cessna",
    "reason": "Needed for Repairs",
    "stage": "Stage 1",
    "unitPrice": "$7,387.75",
    "quantity": "1",
    "totalPrice": "$7,387.75",
    "sourcingLink": "Aircraft Parts Distribution Quote SQT-59937",
    "requestId": "",
    "status": "Received",
    "notes": "Pending Approval; other option: 4 day lead new condition for 7,200.00 Seattle Aviation Solutions SQT855675; Received 26SEP2025"
  },
  {
    "id": "CJMD832-002 (525A)",
    "aircraft": "525A CJ2",
    "name": "landing gear squat switch breakout box",
    "partNumber": "CJMD832-002 (525A)",
    "manufacturer": "Cessna",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 1",
    "unitPrice": "$4,670.00",
    "quantity": "1",
    "totalPrice": "$4,670.00",
    "sourcingLink": "https://aeroval.com/ref/493206/CJMD832-002/",
    "requestId": "",
    "status": "Pending Approval",
    "notes": "Pending Approval"
  },
  {
    "id": "6388014-1 (525B)",
    "aircraft": "525B CJ3",
    "name": "landing gear squat switch breakout box",
    "partNumber": "6388014-1 (525B)",
    "manufacturer": "Cessna",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 1",
    "unitPrice": "$1,995.78",
    "quantity": "1",
    "totalPrice": "$1,995.78",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/6388014-1",
    "requestId": "",
    "status": "Pending Approval",
    "notes": "Pending Approval; Waiting for vendors"
  },
  {
    "id": "R-1798",
    "aircraft": "560 Ultra, 560 Encore, 560 Encore+, 560XL Excel, 560XL-XLS, 560 Citation V, 525 CJ1, 525A CJ2, 525B CJ3",
    "name": "main gear jack pad",
    "partNumber": "R-1798",
    "manufacturer": "Tronair",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 1",
    "unitPrice": "$114.28",
    "quantity": "2",
    "totalPrice": "$228.56",
    "sourcingLink": "https://shop.boeing.com/aviation-supply/search?text=R-1798",
    "requestId": "",
    "status": "Approved",
    "notes": "Sourcing; BJC; Approved"
  },
  {
    "id": "02-0517-0140",
    "aircraft": "525C CJ4, 525 CJ1, 525A CJ2, 525B CJ3, 560 Citation V, 560 Encore, 560 Encore+, 560 Ultra, 560XL Excel, 560XL-XLS, 560XL-XLS+",
    "name": "main jack",
    "partNumber": "02-0517-0140",
    "manufacturer": "Tronair",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 1",
    "unitPrice": "$4,724.12",
    "quantity": "2",
    "totalPrice": "$9,448.24",
    "sourcingLink": "https://pilotjohn.com/new/tronair/02-0517c0140?srsltid=AfmBOoqaLDZMn8bqXp4ISvI-EcRtUxB2H8yPbp83RU2KmFRdJez_51_i",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing; waiting for vendors"
  },
  {
    "id": "IFR 4000",
    "aircraft": "525B CJ3, 525A CJ2, 525 CJ1",
    "name": "Nav/Comm Test Set",
    "partNumber": "IFR 4000",
    "manufacturer": "N/A",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 1",
    "unitPrice": "",
    "quantity": "0",
    "totalPrice": "$0.00",
    "sourcingLink": "https://pilotjohn.com/used/viavi/ifr4000",
    "requestId": "",
    "status": "Owned",
    "notes": "Own Equivilent; Owned"
  },
  {
    "id": "R-2008",
    "aircraft": "560 Ultra, 560 Encore+, 560 Encore, 560XL-XLS, 560XL-XLS+, 560XL Excel, 560 Citation V",
    "name": "nose gear jack pad",
    "partNumber": "R-2008",
    "manufacturer": "Tronair",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 1",
    "unitPrice": "$290.30",
    "quantity": "0",
    "totalPrice": "$0.00",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/R-2008",
    "requestId": "",
    "status": "Received",
    "notes": "Owned; BJC; Approved; Received 26SEP2025"
  },
  {
    "id": "02-0520C0111",
    "aircraft": "525A CJ2, 525B CJ3, 525C CJ4",
    "name": "nose jack",
    "partNumber": "02-0520C0111",
    "manufacturer": "Tronair",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 1",
    "unitPrice": "$3,084.40",
    "quantity": "1",
    "totalPrice": "$3,084.40",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/02-0520C0111",
    "requestId": "",
    "status": "Received",
    "notes": "Pending Approval; Received 26SEP2025"
  },
  {
    "id": "02-0520-0110",
    "aircraft": "525C CJ4, 525 CJ1, 525A CJ2, 525B CJ3, 560 Citation V, 560 Encore, 560 Encore+, 560XL-XLS+, 560XL-XLS, 560XL Excel, 560 Ultra",
    "name": "nose jack",
    "partNumber": "02-0520-0110 (textron gave me the ALT of 02-0520C0111 which is the same as above)",
    "manufacturer": "N/A",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 1",
    "unitPrice": "$3,084.40",
    "quantity": "0",
    "totalPrice": "$0.00",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/02-0520C0111",
    "requestId": "",
    "status": "Pending Approval",
    "notes": "Pending Approval"
  },
  {
    "id": "5520151-1_nose",
    "aircraft": "525A CJ2, 525B CJ3, 525C CJ4",
    "name": "nose jack pad",
    "partNumber": "5520151-1",
    "manufacturer": "Cessna",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 1",
    "unitPrice": "$142.12",
    "quantity": "1",
    "totalPrice": "$142.12",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/5520151-1",
    "requestId": "",
    "status": "Approved",
    "notes": "Sourcing; \"Approved; Zenith has NS with CoC 70.00\""
  },
  {
    "id": "CJMD8A32-004",
    "aircraft": "525A CJ2",
    "name": "nose landing gear test box",
    "partNumber": "CJMD8A32-004",
    "manufacturer": "Cessna",
    "reason": "Need For Advanced Troubleshooting",
    "stage": "Stage 1",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing; Not finding"
  },
  {
    "id": "18821-4",
    "aircraft": "525C CJ4, 525 CJ1, 525A CJ2, 525B CJ3, 560 Citation V, 560 Encore, 560 Encore+, 560 Ultra, 560XL Excel, 560XL-XLS, 560XL-XLS+, Citation X, Citation X+",
    "name": "pitot tube adapter",
    "partNumber": "18821-4",
    "manufacturer": "Nav-Aids",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 1",
    "unitPrice": "$476.67",
    "quantity": "1",
    "totalPrice": "$476.67",
    "sourcingLink": "https://shop.boeing.com/aviation-supply/p/18821-4=5A",
    "requestId": "",
    "status": "Approved",
    "notes": "Pending Approval; Approved"
  },
  {
    "id": "CJMDX21-001",
    "aircraft": "525C CJ4",
    "name": "pressurization test kit adapter",
    "partNumber": "CJMDX21-001 (pilot john is saying that this has been superseded with K-1288)",
    "manufacturer": "Cessna",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 1",
    "unitPrice": "$1,548.76",
    "quantity": "1",
    "totalPrice": "$1,548.76",
    "sourcingLink": "https://pilotjohn.com/new/tronair/k-1288?srsltid=AfmBOoqXrTHATuyyd9k0Ihmjp840bU3lzJT3vq4eVRZfR6SDpXI8lRzx",
    "requestId": "",
    "status": "Received",
    "notes": "Sourcing; Received 26SEP2025"
  },
  {
    "id": "CJMD827-005",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "rudder cable tension rig pin",
    "partNumber": "CJMD827-005",
    "manufacturer": "Cessna",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 1",
    "unitPrice": "$72.86",
    "quantity": "1",
    "totalPrice": "$72.86",
    "sourcingLink": "https://www.aviationpartsinc.com/product/cjmd827-005-tool-after-rudder-rig-pin/?srsltid=AfmBOooS7cQf1FQozvSYBgUuj_tNNbRuNr8fKgOTkmoK-IvVapVoQ6Y-",
    "requestId": "",
    "status": "Approved",
    "notes": "Sourcing; Approved"
  },
  {
    "id": "Type L-30",
    "aircraft": "525B CJ3, 525 CJ1, 525A CJ2, 525C CJ4",
    "name": "Spring Scale",
    "partNumber": "Type L-30",
    "manufacturer": "Amek Aircraft Supplies",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 1",
    "unitPrice": "$39.99",
    "quantity": "1",
    "totalPrice": "$39.99",
    "sourcingLink": "https://www.ebay.com/itm/116350635293?chn=ps&mkevt=1&mkcid=28&google_free_listing_action=view_item&srsltid=AfmBOopYJCN1bNQ4nWT_i0E43E5ZXCtYnaXCABwbo_59_Pewp0k4XEntIq8",
    "requestId": "",
    "status": "Approved",
    "notes": "Owned; Approved"
  },
  {
    "id": "CJMDX12-001",
    "aircraft": "525A CJ2, 525B CJ3, 525C CJ4",
    "name": "strut/oleo servicing",
    "partNumber": "CJMDX12-001",
    "manufacturer": "Cessna",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 1",
    "unitPrice": "",
    "quantity": "1",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "03-5815-0000",
    "aircraft": "525A CJ2, 525B CJ3, 525C CJ4",
    "name": "tail stand",
    "partNumber": "03-5815-0000 (Alt 03A5815C0010)",
    "manufacturer": "Tronair",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 1",
    "unitPrice": "$1,656.00",
    "quantity": "?",
    "totalPrice": "#VALUE!",
    "sourcingLink": "https://pilotjohn.com/new/tronair/03a5815c0010",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "IFR 6000",
    "aircraft": "525 CJ1, 525A CJ2, 525B CJ3, Citation 700",
    "name": "TCAS/DME Tester",
    "partNumber": "IFR 6000",
    "manufacturer": "N/A",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 1",
    "unitPrice": "",
    "quantity": "0",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Owned",
    "notes": "Own Equivilent; BJC"
  },
  {
    "id": "02-0526-0100",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "wing jack",
    "partNumber": "02-0526-0100 and 02-0526-C0110",
    "manufacturer": "Tronair",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 1",
    "unitPrice": "$3,490.42",
    "quantity": "0",
    "totalPrice": "$0.00",
    "sourcingLink": "https://pilotjohn.com/new/tronair/02-0526c0110",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "9912691-1",
    "aircraft": "525C CJ4",
    "name": "EMT Kit (Williams Engnes)",
    "partNumber": "9912691-1",
    "manufacturer": "Cessna",
    "reason": "Need For Advanced Troubleshooting",
    "stage": "Stage 1",
    "unitPrice": "",
    "quantity": "1",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing; need to order sub parts PN: 9912691-7, 9912691-8, TL-110579, TL-221207, TL-99187"
  },
  {
    "id": "CJMD234-105_2",
    "aircraft": "525A CJ2, 525 CJ1, 525B CJ3",
    "name": "angle of attack test box",
    "partNumber": "CJMD234-105",
    "manufacturer": "Cessna",
    "reason": "Needed for Repairs",
    "stage": "Stage 2",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "NK1008346-10",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "bleed air cap(block off) (FJ44-2C)",
    "partNumber": "NK1008346-10",
    "manufacturer": "Cessna",
    "reason": "Needed for Repairs",
    "stage": "Stage 4",
    "unitPrice": "$1,022.34",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/NK1008346-10",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research; Waiting for vendors"
  },
  {
    "id": "CJMD8B71-001",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "bleed air cap(block off) (FJ44-3A)",
    "partNumber": "CJMD8B71-001",
    "manufacturer": "Cessna",
    "reason": "Needed for Repairs",
    "stage": "Stage 4",
    "unitPrice": "$2,677.25",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/CJMD8B71-001",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "T60-1001-C8-1A",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "cable tensionometer",
    "partNumber": "T60-1001-C8-1A",
    "manufacturer": "Pacific Scientific Co",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 2",
    "unitPrice": "$1,250.00",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://shop.boeing.com/aviation-supply/search?text=T60-1001-C8-1A",
    "requestId": "",
    "status": "Not Needed",
    "notes": "Own Equivilent; Not needed, alternate on hand"
  },
  {
    "id": "611-6013-04",
    "aircraft": "525 CJ1, 525A CJ2, 525B CJ3, 525C CJ4",
    "name": "Coaxial Cable (BNC to BNC)",
    "partNumber": "611-6013-04",
    "manufacturer": "Artex Aircraft Supplies",
    "reason": "Needed For Standard Inspections",
    "stage": "Avionics Stage 1",
    "unitPrice": "$246.54",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/611-6013-04",
    "requestId": "",
    "status": "Pending Approval",
    "notes": "Pending Approval"
  },
  {
    "id": "OF49-05542 (CJMD8A27-002)",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "elevator inclinometer locator",
    "partNumber": "OF49-05542 (CJMD8A27-002)",
    "manufacturer": "Cessna",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 2",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "CJMD8C36-001",
    "aircraft": "525C CJ4",
    "name": "engine bleed air cap",
    "partNumber": "CJMD8C36-001",
    "manufacturer": "Cessna",
    "reason": "Optional",
    "stage": "Stage 4",
    "unitPrice": "$3,600.00",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://aeroval.com/ref/493322/CJMDS36-001/",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "6388005-1 (CJMD829-001)",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "hydraulic manifold breakout box",
    "partNumber": "6388005-1 (CJMD829-001)",
    "manufacturer": "Cessna",
    "reason": "Need For Advanced Troubleshooting",
    "stage": "Stage 2",
    "unitPrice": "$3,090.72",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://pilotjohn.com/i/textron/CJMD829-001",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "99-9003-1100 (18-4200-1100)",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "nitrogen charger unit",
    "partNumber": "99-9003-1100 (18-4200-1100)",
    "manufacturer": "Tronair",
    "reason": "Optional",
    "stage": "Stage 2",
    "unitPrice": "$5,553.54",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://pilotjohn.com/new/tronair/18-4200-1100",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "CJMD8A32-004_2",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "nose gear test box",
    "partNumber": "CJMD8A32-004",
    "manufacturer": "Cessna",
    "reason": "Optional",
    "stage": "Stage 2",
    "unitPrice": "$2,199.00",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://aeroval.com/ref/493229/CJMD8A32-004/",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "P86892-4",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "pitot connectors",
    "partNumber": "P86892-4",
    "manufacturer": "Nav-Aids",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 2",
    "unitPrice": "$1,112.27",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/P86892-4",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "8788004-1",
    "aircraft": "525C CJ4",
    "name": "pressurization control breakout box",
    "partNumber": "8788004-1",
    "manufacturer": "Cessna",
    "reason": "Need For Advanced Troubleshooting",
    "stage": "Stage 2",
    "unitPrice": "$2,564.00",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://aeroval.com/ref/474634/8788001-8/",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "CJMD8A27-001",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "rudder check fixture",
    "partNumber": "CJMD8A27-001",
    "manufacturer": "Cessna",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 2",
    "unitPrice": "$10,505.60",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://www.airpowerinc.com/cjmd8c27-001?srsltid=AfmBOopXTOm1EysrQVlJ8XPJ10io6tCmZ4UP9Wy_JVQHrnpADZszTj_p",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "CJMDL27-004",
    "aircraft": "525A CJ2, 525B CJ3, 525C CJ4",
    "name": "rudder pedal tension/clamping",
    "partNumber": "CJMDL27-004",
    "manufacturer": "Cessna",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 2",
    "unitPrice": "$2,400.00",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "Textron",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "CJMD332-101",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "rudder pedal torque tool",
    "partNumber": "CJMD332-101",
    "manufacturer": "Cessna",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 2",
    "unitPrice": "$838.30",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/CJMD332-101",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "CJMD827-003",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "rudder trim tab check fixture",
    "partNumber": "CJMD827-003",
    "manufacturer": "Cessna",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 2",
    "unitPrice": "$978.02",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://www.airpowerinc.com/cjmd332-101?srsltid=AfmBOopVsyuG_PsT4RMmrC4892UhyXqd8pDJ5HLbKv2ZRg3GS1Tw6V0-",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "33410FFAB-125-4",
    "aircraft": "525A CJ2, 525B CJ3, 525C CJ4, 525 CJ1, Citation X, Citation X+, 560XL-XLS+, 560XL-XLS, 560XL Excel, 560 Ultra, 560 Encore+, 560 Encore, Citation 500/501, Citation 550, Citation 650, Citation 700",
    "name": "static port connectors",
    "partNumber": "33410FFAB-125-4",
    "manufacturer": "Nav-Aids",
    "reason": "Needed For Standard Inspections",
    "stage": "700 tooling",
    "unitPrice": "$526.35",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://pilotjohn.com/new/nav-aids-ltd/33410ffab-125-4",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research; 3-4 week lead"
  },
  {
    "id": "ATC 601",
    "aircraft": "525 CJ1, 525A CJ2, 525B CJ3",
    "name": "Transponder Ramp Test Set",
    "partNumber": "ATC 601",
    "manufacturer": "N/A",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 2",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Not Needed",
    "notes": "Own Equivilent; Not needed, alternate on hand"
  },
  {
    "id": "CJMD8A30-001",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "windshield alcohol adjustment kit",
    "partNumber": "CJMD8A30-001",
    "manufacturer": "Cessna",
    "reason": "Needed for Repairs",
    "stage": "Stage 2",
    "unitPrice": "Contact Cessna",
    "quantity": "",
    "totalPrice": "#VALUE!",
    "sourcingLink": "",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research; waiting for vendor"
  },
  {
    "id": "CJMD827-002",
    "aircraft": "525B CJ3, 525C CJ4",
    "name": "AIleron, Elevator & rudder trim freeplay fixture",
    "partNumber": "CJMD827-002",
    "manufacturer": "Cessna",
    "reason": "Optional",
    "stage": "Stage 3",
    "unitPrice": "$18,248.81",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://www.airpowerinc.com/cjmd827-002?srsltid=AfmBOooHwU7e8jJl--45lTVrkvA2CkckRmFnuahrzSaVj5VQrr83dda7",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "99-791",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "anti-skid test set",
    "partNumber": "99-791",
    "manufacturer": "Hydro-Aire",
    "reason": "Optional",
    "stage": "Stage 3",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "99-791-581",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "anti-skid test set adapter cable",
    "partNumber": "99-791-581",
    "manufacturer": "Hydro-Aire",
    "reason": "Optional",
    "stage": "Stage 3",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "500-3000",
    "aircraft": "525 CJ1, 525A CJ2, 525B CJ3, 525C CJ4",
    "name": "Attenuator (30DB)",
    "partNumber": "500-3000",
    "manufacturer": "Artex aircraft supplies",
    "reason": "Need For Advanced Troubleshooting",
    "stage": "Stage 3",
    "unitPrice": "$106.55",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://shop.boeing.com/aviation-supply/search?text=500-3000+Inline+30Db+Attenuator",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "6286005-1",
    "aircraft": "525C CJ4",
    "name": "check valve R&I tool",
    "partNumber": "6286005-1",
    "manufacturer": "Cessna",
    "reason": "Needed for Repairs",
    "stage": "Stage 3",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "CJMD8C27-003",
    "aircraft": "525C CJ4",
    "name": "control wheel leveling tool",
    "partNumber": "CJMD8C27-003",
    "manufacturer": "Cessna",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 3",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "CJMD820-001C",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "dial indicator base wing refinsishing tool kit",
    "partNumber": "CJMD820-001C",
    "manufacturer": "Cessna",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 3",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Not Needed",
    "notes": "Own Equivilent; Not needed, alternate on hand"
  },
  {
    "id": "CJMD756-100",
    "aircraft": "525C CJ4",
    "name": "electric windshield anti-ice test box",
    "partNumber": "CJMD756-100",
    "manufacturer": "Cessna",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 3",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "9912691-1_2",
    "aircraft": "525C CJ4",
    "name": "EMT kit",
    "partNumber": "9912691-1",
    "manufacturer": "Cessna",
    "reason": "Needed for Repairs",
    "stage": "Stage 3",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "08-2021-0000",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "engine build up dolly",
    "partNumber": "08-2021-0000 Also, order Adapter Kit K-2032",
    "manufacturer": "Tronair",
    "reason": "Needed for Repairs",
    "stage": "Stage 3",
    "unitPrice": "$10,378.00",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/08-2021-0000",
    "requestId": "K-2032 is 5,376.00 l",
    "status": "In Research",
    "notes": "In Research; lead time"
  },
  {
    "id": "08-0119-8000 (CJMD871-001)",
    "aircraft": "525A CJ2, 525B CJ3, 525 CJ1, 525C CJ4",
    "name": "engine sling",
    "partNumber": "08-0119-8000 (CJMD871-001)",
    "manufacturer": "Tronair",
    "reason": "Needed for Repairs",
    "stage": "Stage 3",
    "unitPrice": "$1,653.00",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/08-0119-8000",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research; lead time"
  },
  {
    "id": "08-0147C4000",
    "aircraft": "525C CJ4, 525 CJ1, 525A CJ2, 525B CJ3",
    "name": "engine sling",
    "partNumber": "08-0147C4000 or 08-0119-8000",
    "manufacturer": "Tronair",
    "reason": "Needed for Repairs",
    "stage": "Stage 3",
    "unitPrice": "$1,706.00",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/08-0147C4000",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "K-4375",
    "aircraft": "525C CJ4, 525 CJ1, 525A CJ2, 525B CJ3",
    "name": "engine sling adapter",
    "partNumber": "K-4375",
    "manufacturer": "Tronair",
    "reason": "Needed for Repairs",
    "stage": "Stage 3",
    "unitPrice": "$822.00",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/K-4375",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "08-2021C0000",
    "aircraft": "525C CJ4, 525 CJ1, 525A CJ2, 525B CJ3",
    "name": "engine stand",
    "partNumber": "08-2021C0000",
    "manufacturer": "Tronair",
    "reason": "Needed for Repairs",
    "stage": "Stage 3",
    "unitPrice": "$10,378.00",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/08-2021C0000",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "K-4190",
    "aircraft": "525C CJ4, 525 CJ1, 525A CJ2, 525B CJ3",
    "name": "engine stand adapter",
    "partNumber": "K-4190",
    "manufacturer": "Tronair",
    "reason": "Needed for Repairs",
    "stage": "Stage 3",
    "unitPrice": "$6,178.00",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/K-4190",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "1939-6 (CJMD834-003)",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "fuselage vane protractor",
    "partNumber": "1939-6 (CJMD834-003)",
    "manufacturer": "Safe Flight Instrument",
    "reason": "Needed for Repairs",
    "stage": "Stage 3",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "CJMD8C55-001",
    "aircraft": "525C CJ4",
    "name": "horizontal stabilizer assy lifting fixture",
    "partNumber": "CJMD8C55-001",
    "manufacturer": "Cessna",
    "reason": "Needed for Repairs",
    "stage": "Stage 3",
    "unitPrice": "$34,567.93",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/CJMD8C55-001",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "CJMD812-002",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "hydraulic ground power unit",
    "partNumber": "CJMD812-002",
    "manufacturer": "Cessna",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 3",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Owned",
    "notes": "Owned; Owned"
  },
  {
    "id": "CJMD832-005",
    "aircraft": "525A CJ2, 525B CJ3, 525C CJ4",
    "name": "main gear oleo tool",
    "partNumber": "CJMD832-005",
    "manufacturer": "Cessna",
    "reason": "Optional",
    "stage": "Stage 3",
    "unitPrice": "$529.00",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://aeroval.com/ref/493208/CJMD832-005/",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "6388008-1 (CJMD821-001)",
    "aircraft": "525A CJ2",
    "name": "pressurization cart",
    "partNumber": "6388008-1 (CJMD821-001)",
    "manufacturer": "Cessna",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 3",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Not Needed",
    "notes": "Own Equivilent; Not needed, alternate on hand"
  },
  {
    "id": "CJMD8C31-002",
    "aircraft": "525C CJ4",
    "name": "roll force tool",
    "partNumber": "CJMD8C31-002",
    "manufacturer": "Cessna",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 3",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "75-5410-0401-8",
    "aircraft": "525B CJ3",
    "name": "Rubber/Seam Roller",
    "partNumber": "75-5410-0401-8",
    "manufacturer": "N/A",
    "reason": "Needed for Repairs",
    "stage": "Stage 3",
    "unitPrice": "$35.00",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "CJMD8B27-002",
    "aircraft": "525C CJ4",
    "name": "rudder bias torque adapter tool",
    "partNumber": "CJMD8B27-002",
    "manufacturer": "Cessna",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 3",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "CJMD8C31-003",
    "aircraft": "525C CJ4",
    "name": "rudder pedal force tool",
    "partNumber": "CJMD8C31-003",
    "manufacturer": "Cessna",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 3",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "455-9100",
    "aircraft": "525 CJ1, 525A CJ2, 525B CJ3, 525C CJ4",
    "name": "SARSAT Tester",
    "partNumber": "455-9100",
    "manufacturer": "Airtex Systems",
    "reason": "Need For Advanced Troubleshooting",
    "stage": "Stage 3",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "CJMD130-100",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "windshield bleed air anti-ice test tube",
    "partNumber": "CJMD130-100",
    "manufacturer": "Cessna",
    "reason": "Needed for Repairs",
    "stage": "Stage 3",
    "unitPrice": "$533.00",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://aeroval.com/ref/493049/CJMD130-100/",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "CJMD8A33-001",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "wing light tool",
    "partNumber": "CJMD8A33-001",
    "manufacturer": "Cessna",
    "reason": "Optional",
    "stage": "Stage 3",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  },
  {
    "id": "2656-G",
    "aircraft": "525C CJ4",
    "name": "altitude encoder test set",
    "partNumber": "2656-G",
    "manufacturer": "Barfield Instrument",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 4",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "CM429-1",
    "aircraft": "525C CJ4",
    "name": "ARINC 429 PCMCIA card",
    "partNumber": "CM429-1",
    "manufacturer": "Ballard Technology",
    "reason": "Optional",
    "stage": "Stage 4",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "CJMD8C52-004",
    "aircraft": "525C CJ4",
    "name": "cabin door hinge inner eccentric wrench",
    "partNumber": "CJMD8C52-004",
    "manufacturer": "Cessna",
    "reason": "Needed for Repairs",
    "stage": "Stage 4",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "CJMD8C52-003",
    "aircraft": "525C CJ4",
    "name": "cabin door hitch outer eccentric wrench",
    "partNumber": "CJMD8C52-003",
    "manufacturer": "Cessna",
    "reason": "Needed for Repairs",
    "stage": "Stage 4",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "CJMD8C52-002",
    "aircraft": "525C CJ4",
    "name": "cabin door latch inner eccentric wrench",
    "partNumber": "CJMD8C52-002",
    "manufacturer": "Cessna",
    "reason": "Needed for Repairs",
    "stage": "Stage 4",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "CJMD8C52-001",
    "aircraft": "525C CJ4",
    "name": "cabin door latch outer eccentric wrench",
    "partNumber": "CJMD8C52-001",
    "manufacturer": "Cessna",
    "reason": "Needed for Repairs",
    "stage": "Stage 4",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "CJMD8C52-005",
    "aircraft": "525C CJ4",
    "name": "cabin door sight glass wrench",
    "partNumber": "CJMD8C52-005",
    "manufacturer": "Cessna",
    "reason": "Needed for Repairs",
    "stage": "Stage 4",
    "unitPrice": "$8,821.22",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/CJMD8C52-005",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "CJMD156-101",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "calbration standard",
    "partNumber": "CJMD156-101",
    "manufacturer": "Cessna",
    "reason": "Optional",
    "stage": "Stage 4",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "CJMD8C32-001",
    "aircraft": "525C CJ4",
    "name": "camber adjustment tool",
    "partNumber": "CJMD8C32-001",
    "manufacturer": "Cessna",
    "reason": "Needed for Repairs",
    "stage": "Stage 4",
    "unitPrice": "$6,643.00",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/CJMD8C32-001",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "5180002-1",
    "aircraft": "525A CJ2, 525B CJ3, 525C CJ4",
    "name": "control surface balance fixture kit",
    "partNumber": "5180002-1",
    "manufacturer": "Cessna",
    "reason": "Needed for Repairs",
    "stage": "Stage 4",
    "unitPrice": "$1,171.00",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://aeroval.com/ref/995749/5180002-1/",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "8788019-1",
    "aircraft": "525C CJ4",
    "name": "DCU rigging harness",
    "partNumber": "8788019-1",
    "manufacturer": "Cessna",
    "reason": "Needed for Repairs",
    "stage": "Stage 4",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "CJMD8C27-002",
    "aircraft": "525C CJ4",
    "name": "elevator streamline fixture",
    "partNumber": "CJMD8C27-002",
    "manufacturer": "Cessna",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 4",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "CJMD820-001B",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "elliptical wing refinsihing tool kit",
    "partNumber": "CJMD820-001B",
    "manufacturer": "Cessna",
    "reason": "Optional",
    "stage": "Stage 4",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "K-2012",
    "aircraft": "525C CJ4",
    "name": "engine lift adapter",
    "partNumber": "K-2012",
    "manufacturer": "Tronair",
    "reason": "Needed for Repairs",
    "stage": "Stage 4",
    "unitPrice": "$9,966.00",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/K-2012",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "OF49-01483 (CJMD8A27-003)",
    "aircraft": "525A CJ2",
    "name": "left elevator rig boards",
    "partNumber": "OF49-01483 (CJMD8A27-003)",
    "manufacturer": "Cessna",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 4",
    "unitPrice": "$9,045.74",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://www.airpowerinc.com/cjmd8a27-004",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "CJMD832-001",
    "aircraft": "525A CJ2, 525B CJ3, 525C CJ4",
    "name": "main gear oleo tool kit",
    "partNumber": "CJMD832-001",
    "manufacturer": "Cessna",
    "reason": "Needed for Repairs",
    "stage": "Stage 4",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "CJMD832-007",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "main gear trunnion pin bore go gauge",
    "partNumber": "CJMD832-007",
    "manufacturer": "Cessna",
    "reason": "Needed for Repairs",
    "stage": "Stage 4",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "CJMD832-006",
    "aircraft": "525A CJ2",
    "name": "main landing gear trunnion bearing removal",
    "partNumber": "CJMD832-006",
    "manufacturer": "Cessna",
    "reason": "Needed for Repairs",
    "stage": "Stage 4",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "PCB60M",
    "aircraft": "525C CJ4",
    "name": "PCB breakout box",
    "partNumber": "PCB60M",
    "manufacturer": "Cessna",
    "reason": "Need For Advanced Troubleshooting",
    "stage": "Stage 4",
    "unitPrice": "$2,680.00",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://aeroval.com/ref/514810/PCB60/",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "CJMD8C31-001",
    "aircraft": "525C CJ4",
    "name": "pitch force tool",
    "partNumber": "CJMD8C31-001",
    "manufacturer": "Cessna",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 4",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "OF49-01483 (CJMD8A27-004)",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "right elevator rig boards",
    "partNumber": "OF49-01483 (CJMD8A27-004)",
    "manufacturer": "Cessna",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 4",
    "unitPrice": "$9,045.74",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://www.airpowerinc.com/cjmd8a27-004",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "CJMD8C27-001",
    "aircraft": "525C CJ4",
    "name": "rudder check fixture",
    "partNumber": "CJMD8C27-001",
    "manufacturer": "Cessna",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 4",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "33410SM-125-4",
    "aircraft": "525C CJ4",
    "name": "static port adapter",
    "partNumber": "33410SM-125-4",
    "manufacturer": "Nav-Aids",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 4",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "6588002-1",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "throttle switch test box",
    "partNumber": "6588002-1",
    "manufacturer": "Cessna",
    "reason": "Optional",
    "stage": "Stage 4",
    "unitPrice": "$3,241.00",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://aeroval.com/ref/446055/6588002-1/",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "Model 43",
    "aircraft": "525C CJ4",
    "name": "Thruline RF wattmeter",
    "partNumber": "Model 43",
    "manufacturer": "Bird Electronic",
    "reason": "Need For Advanced Troubleshooting",
    "stage": "Stage 4",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "CJMD8A78-001",
    "aircraft": "525A CJ2, 525B CJ3",
    "name": "thrust attenuator rig tool",
    "partNumber": "CJMD8A78-001",
    "manufacturer": "Cessna",
    "reason": "Optional",
    "stage": "Stage 4",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "Dukane Model 42A12",
    "aircraft": "525C CJ4",
    "name": "underwater locator beacon (ULB) test set",
    "partNumber": "Dukane Model 42A12",
    "manufacturer": "Cessna",
    "reason": "Needed For Standard Inspections",
    "stage": "Stage 4",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "ASM 310",
    "aircraft": "525B CJ3",
    "name": "Helium Leak Detector",
    "partNumber": "ASM 310",
    "manufacturer": "Alcatel vaccum products",
    "reason": "Need For Advanced Troubleshooting",
    "stage": "Stage 5",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "CJMD853-001",
    "aircraft": "525A CJ2, 525B CJ3, 525C CJ4",
    "name": "lighting diverter strip locting tool",
    "partNumber": "CJMD853-001",
    "manufacturer": "Cessna",
    "reason": "Optional",
    "stage": "Stage 5",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "CJMD8A32-001_2",
    "aircraft": "525A CJ2, 525B CJ3, 525C CJ4",
    "name": "main gear camber adjustment tool",
    "partNumber": "CJMD8A32-001",
    "manufacturer": "Cessna",
    "reason": "Needed for Repairs",
    "stage": "Stage 5",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "Sourcing",
    "notes": "Sourcing"
  },
  {
    "id": "8288001-1",
    "aircraft": "Citation 700",
    "name": "main landing gear simulator test box",
    "partNumber": "8288001-1",
    "manufacturer": "Textron",
    "reason": "Needed For Standard Inspections",
    "stage": "700 tooling",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/8288001-1",
    "requestId": "",
    "status": "In Research",
    "notes": ""
  },
  {
    "id": "6988012-7",
    "aircraft": "Citation 700",
    "name": "Nose gear simulator test box",
    "partNumber": "6988012-7",
    "manufacturer": "Textron",
    "reason": "Needed For Standard Inspections",
    "stage": "700 tooling",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/6988012-7",
    "requestId": "",
    "status": "In Research",
    "notes": ""
  },
  {
    "id": "P86892-4_2",
    "aircraft": "Citation 700, Citation 500/501, Citation 550, Citation 650",
    "name": "pitot probe adapters",
    "partNumber": "P86892-4",
    "manufacturer": "NAV-AIDS",
    "reason": "Needed For Standard Inspections",
    "stage": "700 tooling",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://pilotjohn.com/new/nav-aids-ltd/p86892-4?srsltid=AfmBOoovs4TWMrD_GKGhPcp0Qf7VQ1M_r2A1ryjkeP3drQsIHE3mqtZ9",
    "requestId": "",
    "status": "In Research",
    "notes": ""
  },
  {
    "id": "R-3053",
    "aircraft": "Citation 700",
    "name": "Main gear jack pad",
    "partNumber": "R-3053",
    "manufacturer": "Tronair Inc.",
    "reason": "Needed For Standard Inspections",
    "stage": "700 tooling",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://www.tronair.com/products/r-3053",
    "requestId": "",
    "status": "In Research",
    "notes": ""
  },
  {
    "id": "R-1808",
    "aircraft": "Citation 700, Citation X",
    "name": "nose gear jack pad",
    "partNumber": "R-1808",
    "manufacturer": "Tronair Inc.",
    "reason": "Needed For Standard Inspections",
    "stage": "700 tooling",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://www.tronair.com/products/r-1808",
    "requestId": "",
    "status": "In Research",
    "notes": ""
  },
  {
    "id": "PCB40, PCB60, or PCB92",
    "aircraft": "Citation 700",
    "name": "PCB extender card",
    "partNumber": "PCB40, PCB60, or PCB92",
    "manufacturer": "Textron",
    "reason": "Needed For Standard Inspections",
    "stage": "700 tooling",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/PCB92",
    "requestId": "",
    "status": "In Research",
    "notes": ""
  },
  {
    "id": "Fluke 712",
    "aircraft": "Citation 700",
    "name": "RTD Calibrator",
    "partNumber": "Fluke 712 RTD calibrator",
    "manufacturer": "Fluke",
    "reason": "Needed For Standard Inspections",
    "stage": "700 tooling",
    "unitPrice": "$2,091.99",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://www.fluke.com/en-us/product/calibration-tools/temperature-calibrators/fluke-712b?srsltid=AfmBOoqMwxbRpoMTBlF1OKs_s9J9J5EDv7YdtX8cQuM3BY93XsG5RkZk",
    "requestId": "",
    "status": "In Research",
    "notes": ""
  },
  {
    "id": "CJMDU32-007A",
    "aircraft": "Citation 700",
    "name": "wheel speed simulator",
    "partNumber": "CJMDU32-007A",
    "manufacturer": "Textron",
    "reason": "Needed For Standard Inspections",
    "stage": "700 tooling",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/CJMDU32-007A",
    "requestId": "",
    "status": "In Research",
    "notes": ""
  },
  {
    "id": "8204541-X",
    "aircraft": "Citation 700",
    "name": "cessna longitude CMC viewer SD card",
    "partNumber": "8204541-X",
    "manufacturer": "Textron",
    "reason": "Needed for Repairs",
    "stage": "700 tooling",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "In Research",
    "notes": ""
  },
  {
    "id": "CJMDX35-001",
    "aircraft": "Citation 700",
    "name": "oxygen flow meter test kit",
    "partNumber": "CJMDX35-001",
    "manufacturer": "Textron",
    "reason": "Needed For Standard Inspections",
    "stage": "700 tooling",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/CJMDX35-001",
    "requestId": "",
    "status": "In Research",
    "notes": ""
  },
  {
    "id": "CJMDS27-015",
    "aircraft": "Citation 700",
    "name": "control wheel leveling bar",
    "partNumber": "CJMDS27-015",
    "manufacturer": "Textron",
    "reason": "Needed For Standard Inspections",
    "stage": "700 tooling",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "In Research",
    "notes": ""
  },
  {
    "id": "model 580",
    "aircraft": "Citation 700",
    "name": "Micro-ohmmeter",
    "partNumber": "model 580",
    "manufacturer": "keithley instruments",
    "reason": "Needed For Standard Inspections",
    "stage": "700 tooling",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "",
    "requestId": "",
    "status": "In Research",
    "notes": ""
  },
  {
    "id": "TS500",
    "aircraft": "Citation 700, 525C CJ4",
    "name": "portable test set (ultrasonic)",
    "partNumber": "TS500",
    "manufacturer": "Dukane seacom inc.",
    "reason": "Needed For Standard Inspections",
    "stage": "700 tooling",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://www.avionteq.com/Dukane-Avionics-TS500-ULB-test-set",
    "requestId": "",
    "status": "In Research",
    "notes": ""
  },
  {
    "id": "6520",
    "aircraft": "525 CJ1, 525A CJ2, 525B CJ3, 525C CJ4, 560 Citation V, 560 Encore, 560 Encore+, 560 Ultra, 560XL Excel, 560XL-XLS, 560XL-XLS+, Citation X, Citation X+, Citation 700, Citation 500/501, Citation 550, Citation 650",
    "name": "portable air data tester",
    "partNumber": "6520 (described by laversab as being designed to test most light jets in general)",
    "manufacturer": "Laversab",
    "reason": "Needed For Standard Inspections",
    "stage": "700 tooling",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://laversab.com/product/model-6250-rvsm-automated-pitot-static-tester-for-light-jets/",
    "requestId": "",
    "status": "In Research",
    "notes": ""
  },
  {
    "id": "5837831-4",
    "aircraft": "Citation 700",
    "name": "EEI download kit",
    "partNumber": "5837831-4",
    "manufacturer": "Textron",
    "reason": "Needed For Standard Inspections",
    "stage": "700 tooling",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/5837831-4",
    "requestId": "",
    "status": "In Research",
    "notes": ""
  },
  {
    "id": "02-7815C0110",
    "aircraft": "Citation 700, 560XL-XLS+, 560XL-XLS, 560XL Excel",
    "name": "Main Landing gear jack",
    "partNumber": "02-7815C0110",
    "manufacturer": "Tronair",
    "reason": "Needed For Standard Inspections",
    "stage": "700 tooling",
    "unitPrice": "",
    "quantity": "",
    "totalPrice": "$0.00",
    "sourcingLink": "https://www.tronair.com/products/02-7815c0110",
    "requestId": "",
    "status": "In Research",
    "notes": "In Research"
  }
]
