import type { PurchasePlanItem } from './types';

export const PURCHASING_PLAN_DATA: PurchasePlanItem[] = [
    {
        id: "PP-001",
        aircraft: "525A CJ2, 525B CJ3, 525C CJ4, 525 CJ1, Citation X, Citation X+, 560XL-XLS+, 560XL-XLS, 560XL Excel, 560 Ultra, 560 Encore+, 560 Encore, Citation 500/501, Citation 550, Citation 650, Citation 700",
        itemType: "Tool",
        name: "static port connectors",
        partNumber: "33410FFAB-125-4",
        manufacturer: "Nav-Aids",
        reason: "Needed For Standard Inspections",
        stage: "700 tooling",
        unitPrice: "$526.35",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://pilotjohn.com/new/nav-aids-ltd/33410ffab-125-4",
        requestId: "",
        status: "In Research",
        notes: "3-4 week lead",
        received: false
    },
    {
        id: "PP-002",
        aircraft: "Citation 700",
        itemType: "Tool",
        name: "main landing gear simulator test box",
        partNumber: "8288001-1",
        manufacturer: "Textron",
        reason: "Needed For Standard Inspections",
        stage: "700 tooling",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/8288001-1",
        requestId: "",
        status: "",
        notes: "",
        received: false
    },
    {
        id: "PP-003",
        aircraft: "Citation 700",
        itemType: "Tool",
        name: "Nose gear simulator test box",
        partNumber: "6988012-7",
        manufacturer: "Textron",
        reason: "Needed For Standard Inspections",
        stage: "700 tooling",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/6988012-7",
        requestId: "",
        status: "",
        notes: "",
        received: false
    },
    {
        id: "PP-004",
        aircraft: "Citation 700, Citation 500/501, Citation 550, Citation 650",
        itemType: "Tool",
        name: "pitot probe adapters",
        partNumber: "P86892-4",
        manufacturer: "NAV-AIDS",
        reason: "Needed For Standard Inspections",
        stage: "700 tooling",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://pilotjohn.com/new/nav-aids-ltd/p86892-4?srsltid=AfmBOoovs4TWMrD_GKGhPcp0Qf7VQ1M_r2A1ryjkeP3drQsIHE3mqtZ9",
        requestId: "",
        status: "",
        notes: "",
        received: false
    },
    {
        id: "PP-005",
        aircraft: "Citation 700",
        itemType: "Tool",
        name: "Main gear jack pad",
        partNumber: "R-3053",
        manufacturer: "Tronair Inc.",
        reason: "Needed For Standard Inspections",
        stage: "700 tooling",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://www.tronair.com/products/r-3053",
        requestId: "",
        status: "",
        notes: "",
        received: false
    },
    {
        id: "PP-006",
        aircraft: "Citation 700, Citation X",
        itemType: "Tool",
        name: "nose gear jack pad",
        partNumber: "R-1808",
        manufacturer: "Tronair Inc.",
        reason: "Needed For Standard Inspections",
        stage: "700 tooling",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://www.tronair.com/products/r-1808",
        requestId: "",
        status: "",
        notes: "",
        received: false
    },
    {
        id: "PP-007",
        aircraft: "Citation 700",
        itemType: "Tool",
        name: "PCB extender card",
        partNumber: "PCB40, PCB60, or PCB92",
        manufacturer: "Textron",
        reason: "Needed For Standard Inspections",
        stage: "700 tooling",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/PCB92",
        requestId: "",
        status: "",
        notes: "",
        received: false
    },
    {
        id: "PP-008",
        aircraft: "Citation 700",
        itemType: "Tool",
        name: "RTD Calibrator",
        partNumber: "Fluke 712 RTD calibrator",
        manufacturer: "Fluke",
        reason: "Needed For Standard Inspections",
        stage: "700 tooling",
        unitPrice: "$2,091.99",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://www.fluke.com/en-us/product/calibration-tools/temperature-calibrators/fluke-712b?srsltid=AfmBOoqMwxbRpoMTBlF1OKs_s9J9J5EDv7YdtX8cQuM3BY93XsG5RkZk",
        requestId: "",
        status: "",
        notes: "",
        received: false
    },
    {
        id: "PP-009",
        aircraft: "Citation 700",
        itemType: "Tool",
        name: "wheel speed simulator",
        partNumber: "CJMDU32-007A",
        manufacturer: "Textron",
        reason: "Needed For Standard Inspections",
        stage: "700 tooling",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/CJMDU32-007A",
        requestId: "",
        status: "",
        notes: "",
        received: false
    },
    {
        id: "PP-010",
        aircraft: "Citation 700",
        itemType: "Tool",
        name: "cessna longitude CMC viewer SD card",
        partNumber: "8204541-X",
        manufacturer: "Textron",
        reason: "Needed for Repairs",
        stage: "700 tooling",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "",
        notes: "",
        received: false
    },
    {
        id: "PP-011",
        aircraft: "Citation 700",
        itemType: "Tool",
        name: "oxygen flow meter test kit",
        partNumber: "CJMDX35-001",
        manufacturer: "Textron",
        reason: "Needed For Standard Inspections",
        stage: "700 tooling",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/CJMDX35-001",
        requestId: "",
        status: "",
        notes: "",
        received: false
    },
    {
        id: "PP-012",
        aircraft: "Citation 700",
        itemType: "Tool",
        name: "control wheel leveling bar",
        partNumber: "CJMDS27-015",
        manufacturer: "Textron",
        reason: "Needed For Standard Inspections",
        stage: "700 tooling",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "",
        notes: "",
        received: false
    },
    {
        id: "PP-013",
        aircraft: "Citation 700",
        itemType: "Tool",
        name: "Micro-ohmmeter",
        partNumber: "model 580",
        manufacturer: "keithley instruments",
        reason: "Needed For Standard Inspections",
        stage: "700 tooling",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "",
        notes: "",
        received: false
    },
    {
        id: "PP-014",
        aircraft: "Citation 700, 525C CJ4",
        itemType: "Tool",
        name: "portable test set (ultrasonic)",
        partNumber: "TS500",
        manufacturer: "Dukane seacom inc.",
        reason: "Needed For Standard Inspections",
        stage: "700 tooling",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://www.avionteq.com/Dukane-Avionics-TS500-ULB-test-set",
        requestId: "",
        status: "",
        notes: "",
        received: false
    },
    {
        id: "PP-015",
        aircraft: "525 CJ1, 525A CJ2, 525B CJ3, 525C CJ4, 560 Citation V, 560 Encore, 560 Encore+, 560 Ultra, 560XL Excel, 560XL-XLS, 560XL-XLS+, Citation X, Citation X+, Citation 700, Citation 500/501, Citation 550, Citation 650",
        itemType: "Tool",
        name: "portable air data tester",
        partNumber: "6520 (described by laversab as being designed to test most light jets in general)",
        manufacturer: "Laversab",
        reason: "Needed For Standard Inspections",
        stage: "700 tooling",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://laversab.com/product/model-6250-rvsm-automated-pitot-static-tester-for-light-jets/",
        requestId: "",
        status: "",
        notes: "",
        received: false
    },
    {
        id: "PP-016",
        aircraft: "Citation 700",
        itemType: "Tool",
        name: "EEI download kit",
        partNumber: "5837831-4",
        manufacturer: "Textron",
        reason: "Needed For Standard Inspections",
        stage: "700 tooling",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/5837831-4",
        requestId: "",
        status: "",
        notes: "",
        received: false
    },
    {
        id: "PP-017",
        aircraft: "Citation 700, 560XL-XLS+, 560XL-XLS, 560XL Excel",
        itemType: "Tool",
        name: "Main Landing gear jack",
        partNumber: "02-7815C0110",
        manufacturer: "Tronair",
        reason: "Needed For Standard Inspections",
        stage: "700 tooling",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://www.tronair.com/products/02-7815c0110",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-018",
        aircraft: "525 CJ1, 525A CJ2, 525B CJ3, 525C CJ4",
        itemType: "Tool",
        name: "Coaxial Cable (BNC to BNC)",
        partNumber: "611-6013-04",
        manufacturer: "Artex Aircraft Supplies",
        reason: "Needed For Standard Inspections",
        stage: "Avionics Stage 1",
        unitPrice: "$246.54",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/611-6013-04",
        requestId: "",
        status: "Pending Approval",
        notes: "",
        received: false
    },
    {
        id: "PP-019",
        aircraft: "525 CJ1, 525A CJ2, 525B CJ3, 525C CJ4, 560 Citation V, 560 Encore, 560 Encore+, 560 Ultra, 560XL Excel, Citation X+, Citation X, 560XL-XLS+, 560XL-XLS, Citation 700",
        itemType: "Consumable",
        name: "grease",
        partNumber: "MIL-PRF-23827C Type I (aeroshell 33)",
        manufacturer: "",
        reason: "Needed For Standard Inspections",
        stage: "Stage 1",
        unitPrice: "$17.20",
        quantity: "4",
        totalPrice: "$68.80",
        sourcingLink: "https://www.aircraftspruce.com/catalog/eppages/aerogrease33.php?clickkey=12005158",
        requestId: "",
        status: "Ordered",
        notes: "Approved",
        received: true
    },
    {
        id: "PP-020",
        aircraft: "525A CJ2, 525 CJ1, 525B CJ3, 525C CJ4, 560 Citation V, 560 Encore, 560 Encore+, 560 Ultra, 560XL Excel, 560XL-XLS, 560XL-XLS+, Citation X, Citation X+",
        itemType: "Consumable",
        name: "",
        partNumber: "LPS03816",
        manufacturer: "",
        reason: "Needed For Standard Inspections",
        stage: "Stage 1",
        unitPrice: "$18.96",
        quantity: "2",
        totalPrice: "$37.92",
        sourcingLink: "https://skygeek.com/lps03816.html?srsltid=AfmBOopQxcRmym8jc8safpg-DGC5Ji3V4fJ2Y-XTrFerGX3kLDANyps4",
        requestId: "RQ25-00010.1",
        status: "Sourcing",
        notes: "Approved",
        received: false
    },
    {
        id: "PP-021",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Consumable",
        name: "windshield scratch removal kit",
        partNumber: "NC-78-1",
        manufacturer: "Micro-Surface products",
        reason: "For Parts Stocking",
        stage: "Stage 1",
        unitPrice: "$27.17",
        quantity: "1",
        totalPrice: "$27.17",
        sourcingLink: "https://www.aircraftspruce.com/catalog/cspages/micromeshstd.php?gad_source=1&gclid=CjwKCAjwktO_BhBrEiwAV70jXuNDuj6bpUetvnf-Ecexqlf4f8YDpx7JhkugPc5tmF9mD2SXyjZgRBoCCI4QAvD_BwE",
        requestId: "RQ25-00011.1",
        status: "Ordered",
        notes: "Approved",
        received: false
    },
    {
        id: "PP-022",
        aircraft: "525 CJ1, 525A CJ2, 525B CJ3",
        itemType: "Part",
        name: "anticollision flash tube assembly",
        partNumber: "03-1390-3000 (alt. 03-1390-0000)",
        manufacturer: "",
        reason: "For Parts Stocking",
        stage: "Stage 1",
        unitPrice: "$3,194.35",
        quantity: "1",
        totalPrice: "$3,194.35",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/03-1390-3000",
        requestId: "RQ25-00012.1",
        status: "Pending Approval",
        notes: "",
        received: false
    },
    {
        id: "PP-023",
        aircraft: "525A CJ2",
        itemType: "Part",
        name: "cotter pin (nose tire installation)",
        partNumber: "MS24665-230 (alt MS24665-231)",
        manufacturer: "",
        reason: "For Parts Stocking",
        stage: "Stage 1",
        unitPrice: "$0.14",
        quantity: "6",
        totalPrice: "$0.84",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/MS24665-230",
        requestId: "RQ25-00013.1",
        status: "Ordered",
        notes: "Approved",
        received: false
    },
    {
        id: "PP-024",
        aircraft: "525 CJ1, 525A CJ2, 525B CJ3, 525C CJ4, Citation X+, Citation X, 560XL-XLS+, 560XL-XLS, 560XL Excel",
        itemType: "Part",
        name: "hydraulic pump installation gasket",
        partNumber: "S3365-1 (alt AS3492-01)",
        manufacturer: "",
        reason: "Needed For Standard Inspections",
        stage: "Stage 1",
        unitPrice: "",
        quantity: "2",
        totalPrice: "$0.00",
        sourcingLink: "https://shop.boeing.com/aviation-supply/p/AS3492-01=15",
        requestId: "RQ25-00014.1",
        status: "Ordered",
        notes: "Approved",
        received: false
    },
    {
        id: "PP-025",
        aircraft: "525 CJ1, 525A CJ2, 525B CJ3, Citation X, 560XL-XLS, 560XL-XLS+",
        itemType: "Part",
        name: "ice detector bulb",
        partNumber: "6838",
        manufacturer: "",
        reason: "For Parts Stocking",
        stage: "Stage 1",
        unitPrice: "$0.34",
        quantity: "2",
        totalPrice: "$0.68",
        sourcingLink: "https://shop.boeing.com/aviation-supply/p/6838=1F",
        requestId: "RQ25-00015.1",
        status: "Ordered",
        notes: "Approved",
        received: false
    },
    {
        id: "PP-026",
        aircraft: "525 CJ1, 525A CJ2, 525B CJ3, Citation X+, Citation X, 560 Citation V, 560 Encore, 560 Encore+, 560 Ultra",
        itemType: "Part",
        name: "landing light bulb",
        partNumber: "Q4681",
        manufacturer: "",
        reason: "For Parts Stocking",
        stage: "Stage 1",
        unitPrice: "$21.19",
        quantity: "2",
        totalPrice: "$42.38",
        sourcingLink: "https://shop.boeing.com/aviation-supply/p/Q4681=1F",
        requestId: "RQ25-00016.1",
        status: "Ordered",
        notes: "Approved",
        received: false
    },
    {
        id: "PP-027",
        aircraft: "525 CJ1, 525A CJ2",
        itemType: "Part",
        name: "main tire",
        partNumber: "9912576-1 (22X7.75-10 12ply) (alt 026-528-0",
        manufacturer: "",
        reason: "For Parts Stocking",
        stage: "Stage 1",
        unitPrice: "$827.26",
        quantity: "1",
        totalPrice: "$827.26",
        sourcingLink: "https://shop.boeing.com/aviation-supply/search?text=026-528-0",
        requestId: "RQ25-00017.1",
        status: "Ordered",
        notes: "Approved",
        received: false
    },
    {
        id: "PP-028",
        aircraft: "525 CJ1, 525A CJ2",
        itemType: "Part",
        name: "nose tire",
        partNumber: "030-611-0 (alt. 184F68-1 or 9914070-1)",
        manufacturer: "",
        reason: "For Parts Stocking",
        stage: "Stage 1",
        unitPrice: "$689.95",
        quantity: "1",
        totalPrice: "$689.95",
        sourcingLink: "https://shop.boeing.com/aviation-supply/search?text=030-611-0",
        requestId: "RQ25-00018.1",
        status: "Pending Approval",
        notes: "",
        received: false
    },
    {
        id: "PP-029",
        aircraft: "525 CJ1, 525A CJ2, 525B CJ3, 525C CJ4, 560 Citation V, 560 Encore, 560 Encore+, 560 Ultra, 560XL Excel, 560XL-XLS, 560XL-XLS+, Citation X, Citation X+",
        itemType: "Part",
        name: "oring for brake reserivor air filter (X2)",
        partNumber: "MS28778-6",
        manufacturer: "",
        reason: "For Parts Stocking",
        stage: "Stage 1",
        unitPrice: "$1.03",
        quantity: "2",
        totalPrice: "$2.06",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/MS28778-6",
        requestId: "RQ25-00019.1",
        status: "Ordered",
        notes: "Approved",
        received: false
    },
    {
        id: "PP-030",
        aircraft: "525 CJ1",
        itemType: "Part",
        name: "oring fuel drain valve",
        partNumber: "M25988/1-010",
        manufacturer: "",
        reason: "Needed for Repairs",
        stage: "Stage 1",
        unitPrice: "$0.55",
        quantity: "2",
        totalPrice: "$1.10",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/M25988-1-010",
        requestId: "RQ25-00021.1",
        status: "Ordered",
        notes: "Approved",
        received: false
    },
    {
        id: "PP-031",
        aircraft: "525 CJ1, 525A CJ2, 525B CJ3, 525C CJ4, 560 Citation V, 560 Encore, 560 Encore+, 560 Ultra, 560XL Excel, 560XL-XLS, 560XL-XLS+",
        itemType: "Part",
        name: "oring fuel drain valve",
        partNumber: "MS29513-020",
        manufacturer: "",
        reason: "For Parts Stocking",
        stage: "Stage 1",
        unitPrice: "$0.37",
        quantity: "2",
        totalPrice: "$0.74",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/MS29513-020",
        requestId: "RQ25-00020.1",
        status: "Ordered",
        notes: "Approved",
        received: false
    },
    {
        id: "PP-032",
        aircraft: "525 CJ1",
        itemType: "Part",
        name: "power supply nav and anticollision lights",
        partNumber: "04-1502-1408",
        manufacturer: "",
        reason: "For Parts Stocking",
        stage: "Stage 1",
        unitPrice: "",
        quantity: "1",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "RQ25-00022.1",
        status: "Sourcing",
        notes: "waiting for vendors",
        received: false
    },
    {
        id: "PP-033",
        aircraft: "525 CJ1, 525A CJ2, 525B CJ3, Citation X, 560XL-XLS, 560XL-XLS+",
        itemType: "Part",
        name: "recogniton bulb",
        partNumber: "34-0226010-91",
        manufacturer: "",
        reason: "For Parts Stocking",
        stage: "Stage 1",
        unitPrice: "$77.14",
        quantity: "1",
        totalPrice: "$77.14",
        sourcingLink: "https://shop.boeing.com/aviation-supply/p/34-0226010-91=3Y",
        requestId: "RQ25-00023.1",
        status: "Ordered",
        notes: "Approved",
        received: false
    },
    {
        id: "PP-034",
        aircraft: "525 CJ1, 525A CJ2, 525B CJ3, 525C CJ4, 560XL-XLS, 560XL-XLS+",
        itemType: "Part",
        name: "screw, wing fuel panel",
        partNumber: "S3322S10-15",
        manufacturer: "",
        reason: "For Parts Stocking",
        stage: "Stage 1",
        unitPrice: "$0.47",
        quantity: "30",
        totalPrice: "$14.10",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/S3322S10-15",
        requestId: "RQ25-00024.1",
        status: "Ordered",
        notes: "Approved",
        received: false
    },
    {
        id: "PP-035",
        aircraft: "525 CJ1, 525A CJ2, 525B CJ3, 525C CJ4, Citation X, Citation X+, 560XL-XLS, 560XL-XLS+",
        itemType: "Part",
        name: "starter/generator gasket (X2 per installation)",
        partNumber: "S3365-1 (alt. AS3492-01)",
        manufacturer: "",
        reason: "For Parts Stocking",
        stage: "Stage 1",
        unitPrice: "$2.69",
        quantity: "2",
        totalPrice: "$5.38",
        sourcingLink: "https://shop.boeing.com/aviation-supply/p/AS3492-01=15",
        requestId: "RQ25-00025.1",
        status: "Ordered",
        notes: "Approved",
        received: false
    },
    {
        id: "PP-036",
        aircraft: "525 CJ1",
        itemType: "Part",
        name: "starter/generator oring",
        partNumber: "M83248/1-113",
        manufacturer: "",
        reason: "For Parts Stocking",
        stage: "Stage 1",
        unitPrice: "$0.46",
        quantity: "2",
        totalPrice: "$0.92",
        sourcingLink: "https://shop.boeing.com/aviation-supply/p/M83248-1-113=15",
        requestId: "RQ25-00027.1",
        status: "Ordered",
        notes: "Approved",
        received: false
    },
    {
        id: "PP-037",
        aircraft: "525 CJ1, 525A CJ2, 560XL-XLS, 560XL-XLS+",
        itemType: "Part",
        name: "tail navigation light bulb",
        partNumber: "1638",
        manufacturer: "",
        reason: "For Parts Stocking",
        stage: "Stage 1",
        unitPrice: "$2.58",
        quantity: "2",
        totalPrice: "$5.16",
        sourcingLink: "https://shop.boeing.com/aviation-supply/p/1638=18",
        requestId: "RQ25-00028.1",
        status: "Ordered",
        notes: "Approved",
        received: false
    },
    {
        id: "PP-038",
        aircraft: "525 CJ1, 525A CJ2, 525B CJ3, 560 Citation V, 560 Encore, 560 Encore+",
        itemType: "Part",
        name: "wing inspection light bulb",
        partNumber: "A-7079B-24",
        manufacturer: "",
        reason: "For Parts Stocking",
        stage: "Stage 1",
        unitPrice: "$24.33",
        quantity: "2",
        totalPrice: "$48.66",
        sourcingLink: "https://shop.boeing.com/aviation-supply/p/A7079B24=5V",
        requestId: "RQ25-00029.1",
        status: "Ordered",
        notes: "Approved",
        received: false
    },
    {
        id: "PP-039",
        aircraft: "525 CJ1, 525A CJ2",
        itemType: "Part",
        name: "wing navigation light bulb",
        partNumber: "03-2111-0000 (alt A7512-24)",
        manufacturer: "",
        reason: "For Parts Stocking",
        stage: "Stage 1",
        unitPrice: "$25.22",
        quantity: "2",
        totalPrice: "$50.44",
        sourcingLink: "https://shop.boeing.com/aviation-supply/p/A7512-24=5V",
        requestId: "RQ25-00030.1",
        status: "Ordered",
        notes: "Approved",
        received: false
    },
    {
        id: "PP-040",
        aircraft: "525 CJ1, 525A CJ2, 525B CJ3, 525C CJ4, 560 Citation V, 560 Encore, 560 Encore+, 560 Ultra, Citation X+, Citation X, 560XL-XLS+, 560XL-XLS, 560XL Excel",
        itemType: "Tool",
        name: "Robo Mule",
        partNumber: "MM-3200",
        manufacturer: "Alberth Air Parts",
        reason: "Needed For Standard Inspections",
        stage: "Stage 1",
        unitPrice: "$4,950.00",
        quantity: "1",
        totalPrice: "$4,950.00",
        sourcingLink: "https://alberthaviation.com/products/hydraulic-mule/",
        requestId: "RQ25-00026.1",
        status: "Approved",
        notes: "Received 26SEP2025",
        received: true
    },
    {
        id: "PP-041",
        aircraft: "525B CJ3, 525A CJ2, 525C CJ4, 525 CJ1",
        itemType: "Tool",
        name: "28 volt power supply",
        partNumber: "DCS33-33E",
        manufacturer: "",
        reason: "Needed For Standard Inspections",
        stage: "Stage 1",
        unitPrice: "",
        quantity: "0",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "RQ25-00031.1",
        status: "Both",
        notes: "Not needed, alternate on hand",
        received: false
    },
    {
        id: "PP-042",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "cabin pressurization test cart adapter kit",
        partNumber: "K-1288",
        manufacturer: "Tronair",
        reason: "Needed For Standard Inspections",
        stage: "Stage 1",
        unitPrice: "$1,632.00",
        quantity: "1",
        totalPrice: "$1,632.00",
        sourcingLink: "Proserv Aviation Quote Q18107",
        requestId: "RQ25-00032.1",
        status: "Approved",
        notes: "Approved",
        received: false
    },
    {
        id: "PP-043",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "flap breakout box",
        partNumber: "8788005-1",
        manufacturer: "Cessna",
        reason: "Needed for Repairs",
        stage: "Stage 1",
        unitPrice: "$5,140.20",
        quantity: "1",
        totalPrice: "$5,140.20",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/8788005-1",
        requestId: "RQ25-00033.1",
        status: "Sourcing",
        notes: "Received 26SEP2025",
        received: true
    },
    {
        id: "PP-044",
        aircraft: "525C CJ4, 525 CJ1, 525A CJ2, 525B CJ3, 560 Encore+, 560 Citation V, 560 Encore, 560 Ultra, 560XL Excel, 560XL-XLS, 560XL-XLS+, Citation X, Citation X+",
        itemType: "Tool",
        name: "fuel drain valve removal tool",
        partNumber: "CJMD128-001",
        manufacturer: "Cessna",
        reason: "Needed for Repairs",
        stage: "Stage 1",
        unitPrice: "$70.06",
        quantity: "0",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/CJMD128-001",
        requestId: "",
        status: "Approved",
        notes: "Approved",
        received: false
    },
    {
        id: "PP-045",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "fuel quantity test set",
        partNumber: "6388012-1 (CJMD828-002)",
        manufacturer: "Cessna",
        reason: "Need For Advanced Troubleshooting",
        stage: "Stage 1",
        unitPrice: "$6,322.00",
        quantity: "1",
        totalPrice: "$6,322.00",
        sourcingLink: "https://aeroval.com/ref/493202/CJMD828-002/",
        requestId: "",
        status: "Sourcing",
        notes: "waiting for vendors",
        received: false
    },
    {
        id: "PP-046",
        aircraft: "525C CJ4, 525 CJ1, 525A CJ2, 525B CJ3, 560 Citation V, 560 Encore, 560 Encore+, 560 Ultra, 560XL-XLS, 560XL-XLS+, 560XL Excel",
        itemType: "Tool",
        name: "jack pad adapter",
        partNumber: "5520151-1",
        manufacturer: "Cessna",
        reason: "Needed For Standard Inspections",
        stage: "Stage 1",
        unitPrice: "$142.12",
        quantity: "0",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/5520151-1",
        requestId: "",
        status: "Approved\nZenith has NS with CoC for 70.00",
        notes: "Received 26SEP2025",
        received: true
    },
    {
        id: "PP-047",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "landing gear simulator test box",
        partNumber: "8788001-8",
        manufacturer: "Cessna",
        reason: "Needed for Repairs",
        stage: "Stage 1",
        unitPrice: "$7,387.75",
        quantity: "1",
        totalPrice: "$7,387.75",
        sourcingLink: "Aircraft Parts Distribution Quote SQT-59937",
        requestId: "",
        status: "Pending Approval",
        notes: "other option: 4 day lead new condition for 7,200.00 Seattle Aviation Solutions SQT855675\nReceived 26SEP2025",
        received: true
    },
    {
        id: "PP-048",
        aircraft: "525A CJ2",
        itemType: "Tool",
        name: "landing gear squat switch breakout box",
        partNumber: "CJMD832-002 (525A)",
        manufacturer: "Cessna",
        reason: "Needed For Standard Inspections",
        stage: "Stage 1",
        unitPrice: "$4,670.00",
        quantity: "1",
        totalPrice: "$4,670.00",
        sourcingLink: "https://aeroval.com/ref/493206/CJMD832-002/",
        requestId: "",
        status: "Pending Approval",
        notes: "",
        received: false
    },
    {
        id: "PP-049",
        aircraft: "525B CJ3",
        itemType: "Tool",
        name: "landing gear squat switch breakout box",
        partNumber: "6388014-1 (525B)",
        manufacturer: "Cessna",
        reason: "Needed For Standard Inspections",
        stage: "Stage 1",
        unitPrice: "$1,995.78",
        quantity: "1",
        totalPrice: "$1,995.78",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/6388014-1",
        requestId: "",
        status: "Pending Approval",
        notes: "Waiting for vendors",
        received: false
    },
    {
        id: "PP-050",
        aircraft: "560 Ultra, 560 Encore, 560 Encore+, 560XL Excel, 560XL-XLS, 560 Citation V, 525 CJ1, 525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "main gear jack pad",
        partNumber: "R-1798",
        manufacturer: "Tronair",
        reason: "Needed For Standard Inspections",
        stage: "Stage 1",
        unitPrice: "$114.28",
        quantity: "2",
        totalPrice: "$228.56",
        sourcingLink: "https://shop.boeing.com/aviation-supply/search?text=R-1798",
        requestId: "",
        status: "Approved",
        notes: "",
        received: false
    },
    {
        id: "PP-051",
        aircraft: "525C CJ4, 525 CJ1, 525A CJ2, 525B CJ3, 560 Citation V, 560 Encore, 560 Encore+, 560 Ultra, 560XL Excel, 560XL-XLS, 560XL-XLS+",
        itemType: "Tool",
        name: "main jack",
        partNumber: "02-0517-0140",
        manufacturer: "Tronair",
        reason: "Needed For Standard Inspections",
        stage: "Stage 1",
        unitPrice: "$4,724.12",
        quantity: "2",
        totalPrice: "$9,448.24",
        sourcingLink: "https://pilotjohn.com/new/tronair/02-0517c0140?srsltid=AfmBOoqaLDZMn8bqXp4ISvI-EcRtUxB2H8yPbp83RU2KmFRdJez_51_i",
        requestId: "",
        status: "Sourcing",
        notes: "waiting for vendors",
        received: false
    },
    {
        id: "PP-052",
        aircraft: "525B CJ3, 525A CJ2, 525 CJ1",
        itemType: "Tool",
        name: "Nav/Comm Test Set",
        partNumber: "IFR 4000",
        manufacturer: "",
        reason: "Needed For Standard Inspections",
        stage: "Stage 1",
        unitPrice: "",
        quantity: "0",
        totalPrice: "$0.00",
        sourcingLink: "https://pilotjohn.com/used/viavi/ifr4000",
        requestId: "",
        status: "Owned",
        notes: "",
        received: false
    },
    {
        id: "PP-053",
        aircraft: "560 Ultra, 560 Encore+, 560 Encore, 560XL-XLS, 560XL-XLS+, 560XL Excel, 560 Citation V",
        itemType: "Tool",
        name: "nose gear jack pad",
        partNumber: "R-2008",
        manufacturer: "Tronair",
        reason: "Needed For Standard Inspections",
        stage: "Stage 1",
        unitPrice: "$290.30",
        quantity: "0",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/R-2008",
        requestId: "",
        status: "Approved",
        notes: "Received 26SEP2025",
        received: true
    },
    {
        id: "PP-054",
        aircraft: "525A CJ2, 525B CJ3, 525C CJ4",
        itemType: "Tool",
        name: "nose jack",
        partNumber: "02-0520C0111",
        manufacturer: "Tronair",
        reason: "Needed For Standard Inspections",
        stage: "Stage 1",
        unitPrice: "$3,084.40",
        quantity: "1",
        totalPrice: "$3,084.40",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/02-0520C0111",
        requestId: "",
        status: "Pending Approval",
        notes: "Received 26SEP2025",
        received: true
    },
    {
        id: "PP-055",
        aircraft: "525C CJ4, 525 CJ1, 525A CJ2, 525B CJ3, 560 Citation V, 560 Encore, 560 Encore+, 560XL-XLS+, 560XL-XLS, 560XL Excel, 560 Ultra",
        itemType: "Tool",
        name: "nose jack",
        partNumber: "02-0520-0110 (textron gave me the ALT of 02-0520C0111 which is the same as above)",
        manufacturer: "",
        reason: "Needed For Standard Inspections",
        stage: "Stage 1",
        unitPrice: "$3,084.40",
        quantity: "0",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/02-0520C0111",
        requestId: "",
        status: "Pending Approval",
        notes: "",
        received: false
    },
    {
        id: "PP-056",
        aircraft: "525A CJ2, 525B CJ3, 525C CJ4",
        itemType: "Tool",
        name: "nose jack pad",
        partNumber: "5520151-1",
        manufacturer: "Cessna",
        reason: "Needed For Standard Inspections",
        stage: "Stage 1",
        unitPrice: "$142.12",
        quantity: "1",
        totalPrice: "$142.12",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/5520151-1",
        requestId: "",
        status: "Approved\nZenith has NS with CoC 70.00",
        notes: "",
        received: false
    },
    {
        id: "PP-057",
        aircraft: "525A CJ2",
        itemType: "Tool",
        name: "nose landing gear test box",
        partNumber: "CJMD8A32-004",
        manufacturer: "Cessna",
        reason: "Need For Advanced Troubleshooting",
        stage: "Stage 1",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "Not finding",
        received: false
    },
    {
        id: "PP-058",
        aircraft: "525C CJ4, 525 CJ1, 525A CJ2, 525B CJ3, 560 Citation V, 560 Encore, 560 Encore+, 560 Ultra, 560XL Excel, 560XL-XLS, 560XL-XLS+, Citation X, Citation X+",
        itemType: "Tool",
        name: "pitot tube adapter",
        partNumber: "18821-4",
        manufacturer: "Nav-Aids",
        reason: "Needed For Standard Inspections",
        stage: "Stage 1",
        unitPrice: "$476.67",
        quantity: "1",
        totalPrice: "$476.67",
        sourcingLink: "https://shop.boeing.com/aviation-supply/p/18821-4=5A",
        requestId: "",
        status: "Approved",
        notes: "",
        received: false
    },
    {
        id: "PP-059",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "pressurization test kit adapter",
        partNumber: "CJMDX21-001 (pilot john is saying that this has been superseded with K-1288)",
        manufacturer: "Cessna",
        reason: "Needed For Standard Inspections",
        stage: "Stage 1",
        unitPrice: "$1,548.76",
        quantity: "1",
        totalPrice: "$1,548.76",
        sourcingLink: "https://pilotjohn.com/new/tronair/k-1288?srsltid=AfmBOoqXrTHATuyyd9k0Ihmjp840bU3lzJT3vq4eVRZfR6SDpXI8lRzx",
        requestId: "",
        status: "Sourcing",
        notes: "Received 26SEP2025",
        received: true
    },
    {
        id: "PP-060",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "rudder cable tension rig pin",
        partNumber: "CJMD827-005",
        manufacturer: "Cessna",
        reason: "Needed For Standard Inspections",
        stage: "Stage 1",
        unitPrice: "$72.86",
        quantity: "1",
        totalPrice: "$72.86",
        sourcingLink: "https://www.aviationpartsinc.com/product/cjmd827-005-tool-after-rudder-rig-pin/?srsltid=AfmBOooS7cQf1FQozvSYBgUuj_tNNbRuNr8fKgOTkmoK-IvVapVoQ6Y-",
        requestId: "",
        status: "Approved",
        notes: "",
        received: false
    },
    {
        id: "PP-061",
        aircraft: "525B CJ3, 525 CJ1, 525A CJ2, 525C CJ4",
        itemType: "Tool",
        name: "Spring Scale",
        partNumber: "Type L-30",
        manufacturer: "Amek Aircraft Supplies",
        reason: "Needed For Standard Inspections",
        stage: "Stage 1",
        unitPrice: "$39.99",
        quantity: "1",
        totalPrice: "$39.99",
        sourcingLink: "https://www.ebay.com/itm/116350635293?chn=ps&mkevt=1&mkcid=28&google_free_listing_action=view_item&srsltid=AfmBOopYJCN1bNQ4nWT_i0E43E5ZXCtYnaXCABwbo_59_Pewp0k4XEntIq8",
        requestId: "",
        status: "Approved",
        notes: "",
        received: false
    },
    {
        id: "PP-062",
        aircraft: "525A CJ2, 525B CJ3, 525C CJ4",
        itemType: "Tool",
        name: "strut/oleo servicing",
        partNumber: "CJMDX12-001",
        manufacturer: "Cessna",
        reason: "Needed For Standard Inspections",
        stage: "Stage 1",
        unitPrice: "",
        quantity: "1",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-063",
        aircraft: "525A CJ2, 525B CJ3, 525C CJ4",
        itemType: "Tool",
        name: "tail stand",
        partNumber: "03-5815-0000 (Alt 03A5815C0010)",
        manufacturer: "Tronair",
        reason: "Needed For Standard Inspections",
        stage: "Stage 1",
        unitPrice: "$1,656.00",
        quantity: "?",
        totalPrice: "#VALUE!",
        sourcingLink: "https://pilotjohn.com/new/tronair/03a5815c0010",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-064",
        aircraft: "525 CJ1, 525A CJ2, 525B CJ3, Citation 700",
        itemType: "Tool",
        name: "TCAS/DME Tester",
        partNumber: "IFR 6000",
        manufacturer: "",
        reason: "Needed For Standard Inspections",
        stage: "Stage 1",
        unitPrice: "",
        quantity: "0",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "BJC",
        notes: "",
        received: false
    },
    {
        id: "PP-065",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "wing jack",
        partNumber: "02-0526-0100 and 02-0526-C0110",
        manufacturer: "Tronair",
        reason: "Needed For Standard Inspections",
        stage: "Stage 1",
        unitPrice: "$3,490.42",
        quantity: "0",
        totalPrice: "$0.00",
        sourcingLink: "https://pilotjohn.com/new/tronair/02-0526c0110",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-066",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "EMT Kit (Williams Engnes)",
        partNumber: "9912691-1",
        manufacturer: "Cessna",
        reason: "Need For Advanced Troubleshooting",
        stage: "Stage 1",
        unitPrice: "",
        quantity: "1",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "need to order sub parts PN: 9912691-7, 9912691-8, TL-110579, TL-221207, TL-99187",
        received: false
    },
    {
        id: "PP-067",
        aircraft: "525 CJ1, 525A CJ2, 525B CJ3, 560 Citation V, 560 Encore, 560 Encore+",
        itemType: "Part",
        name: "door seal",
        partNumber: "R860086",
        manufacturer: "Sold in 14ft increments",
        reason: "For Parts Stocking",
        stage: "Stage 2",
        unitPrice: "$48.44",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/R860086",
        requestId: "",
        status: "Pending Approval",
        notes: "Approved, but need quantity",
        received: false
    },
    {
        id: "PP-068",
        aircraft: "525 CJ1, 525A CJ2, 525B CJ3, 525C CJ4, 560XL-XLS, 560XL-XLS+, 560 Citation V, 560 Encore, 560 Encore+, 560 Ultra",
        itemType: "Part",
        name: "drain valve fuel",
        partNumber: "9912083-2",
        manufacturer: "",
        reason: "For Parts Stocking",
        stage: "Stage 2",
        unitPrice: "$175.64",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/9912083-2",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-069",
        aircraft: "525B CJ3",
        itemType: "Part",
        name: "main tire",
        partNumber: "9912709-1 (026-617-1)",
        manufacturer: "",
        reason: "For Parts Stocking",
        stage: "Stage 2",
        unitPrice: "$1,329.50",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://www.aircraftspruce.com/catalog/lgpages/michelinairtires_06-03029.php?clickkey=481330",
        requestId: "",
        status: "",
        notes: "This is a tire or a tire and wheel assy?",
        received: false
    },
    {
        id: "PP-070",
        aircraft: "525B CJ3",
        itemType: "Part",
        name: "nose tire",
        partNumber: "9912706-1 or 9912706-2",
        manufacturer: "",
        reason: "For Parts Stocking",
        stage: "Stage 2",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "",
        notes: "not finding. same quest as above",
        received: false
    },
    {
        id: "PP-071",
        aircraft: "525B CJ3",
        itemType: "Part",
        name: "o-ring main tire",
        partNumber: "140-327525",
        manufacturer: "",
        reason: "For Parts Stocking",
        stage: "Stage 2",
        unitPrice: "$129.96",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/140-327525",
        requestId: "",
        status: "",
        notes: "",
        received: false
    },
    {
        id: "PP-072",
        aircraft: "525A CJ2, 525 CJ1, 525B CJ3",
        itemType: "Tool",
        name: "angle of attack test box",
        partNumber: "CJMD234-105",
        manufacturer: "Cessna",
        reason: "Needed for Repairs",
        stage: "Stage 2",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-073",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "cable tensionometer",
        partNumber: "T60-1001-C8-1A",
        manufacturer: "Pacific Scientific Co",
        reason: "Needed For Standard Inspections",
        stage: "Stage 2",
        unitPrice: "$1,250.00",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://shop.boeing.com/aviation-supply/search?text=T60-1001-C8-1A",
        requestId: "",
        status: "Own Equivilent",
        notes: "Not needed, alternate on hand",
        received: false
    },
    {
        id: "PP-074",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "elevator inclinometer locator",
        partNumber: "OF49-05542 (CJMD8A27-002)",
        manufacturer: "Cessna",
        reason: "Needed For Standard Inspections",
        stage: "Stage 2",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-075",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "hydraulic manifold breakout box",
        partNumber: "6388005-1 (CJMD829-001)",
        manufacturer: "Cessna",
        reason: "Need For Advanced Troubleshooting",
        stage: "Stage 2",
        unitPrice: "$3,090.72",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://pilotjohn.com/i/textron/CJMD829-001",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-076",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "nitrogen charger unit",
        partNumber: "99-9003-1100 (18-4200-1100)",
        manufacturer: "Tronair",
        reason: "Optional",
        stage: "Stage 2",
        unitPrice: "$5,553.54",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://pilotjohn.com/new/tronair/18-4200-1100",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-077",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "nose gear test box",
        partNumber: "CJMD8A32-004",
        manufacturer: "Cessna",
        reason: "Optional",
        stage: "Stage 2",
        unitPrice: "$2,199.00",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://aeroval.com/ref/493229/CJMD8A32-004/",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-078",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "pitot connectors",
        partNumber: "P86892-4",
        manufacturer: "Nav-Aids",
        reason: "Needed For Standard Inspections",
        stage: "Stage 2",
        unitPrice: "$1,112.27",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/P86892-4",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-079",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "pressurization control breakout box",
        partNumber: "8788004-1",
        manufacturer: "Cessna",
        reason: "Need For Advanced Troubleshooting",
        stage: "Stage 2",
        unitPrice: "$2,564.00",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://aeroval.com/ref/474634/8788001-8/",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-080",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "rudder check fixture",
        partNumber: "CJMD8A27-001",
        manufacturer: "Cessna",
        reason: "Needed For Standard Inspections",
        stage: "Stage 2",
        unitPrice: "$10,505.60",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://www.airpowerinc.com/cjmd8c27-001?srsltid=AfmBOopXTOm1EysrQVlJ8XPJ10io6tCmZ4UP9Wy_JVQHrnpADZszTj_p",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-081",
        aircraft: "525A CJ2, 525B CJ3, 525C CJ4",
        itemType: "Tool",
        name: "rudder pedal tension/clamping",
        partNumber: "CJMDL27-004",
        manufacturer: "Cessna",
        reason: "Needed For Standard Inspections",
        stage: "Stage 2",
        unitPrice: "$2,400.00",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "Textron",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-082",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "rudder pedal torque tool",
        partNumber: "CJMD332-101",
        manufacturer: "Cessna",
        reason: "Needed For Standard Inspections",
        stage: "Stage 2",
        unitPrice: "$838.30",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/CJMD332-101",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-083",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "rudder trim tab check fixture",
        partNumber: "CJMD827-003",
        manufacturer: "Cessna",
        reason: "Needed For Standard Inspections",
        stage: "Stage 2",
        unitPrice: "$978.02",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://www.airpowerinc.com/cjmd332-101?srsltid=AfmBOopVsyuG_PsT4RMmrC4892UhyXqd8pDJ5HLbKv2ZRg3GS1Tw6V0-",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-084",
        aircraft: "525 CJ1, 525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "Transponder Ramp Test Set",
        partNumber: "ATC 601",
        manufacturer: "",
        reason: "Needed For Standard Inspections",
        stage: "Stage 2",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Own Equivilent",
        notes: "Not needed, alternate on hand",
        received: false
    },
    {
        id: "PP-085",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "windshield alcohol adjustment kit",
        partNumber: "CJMD8A30-001",
        manufacturer: "Cessna",
        reason: "Needed for Repairs",
        stage: "Stage 2",
        unitPrice: "Contact Cessna",
        quantity: "",
        totalPrice: "#VALUE!",
        sourcingLink: "",
        requestId: "",
        status: "In Research",
        notes: "waiting for vendor",
        received: false
    },
    {
        id: "PP-086",
        aircraft: "525B CJ3",
        itemType: "Manual/CMM",
        name: "aircell Axxess II Satcom System Users Manuals",
        partNumber: "D12058",
        manufacturer: "Aircell",
        reason: "Need For Advanced Troubleshooting",
        stage: "Stage 3",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://www.scribd.com/document/667046161/D12058-AirCellAxxessUsers",
        requestId: "",
        status: "In Research",
        notes: "Please confirm link",
        received: false
    },
    {
        id: "PP-087",
        aircraft: "525 CJ1, 525A CJ2, 525B CJ3",
        itemType: "Part",
        name: "brake reservior air filter assembly",
        partNumber: "AN6240-1",
        manufacturer: "",
        reason: "For Parts Stocking",
        stage: "Stage 3",
        unitPrice: "$532.71",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/AN6240-1",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-088",
        aircraft: "525 CJ1, 525A CJ2, 525B CJ3, 525C CJ4",
        itemType: "Part",
        name: "hydraulic filter",
        partNumber: "9912579-5",
        manufacturer: "",
        reason: "For Parts Stocking",
        stage: "Stage 3",
        unitPrice: "$3,400.13",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/9912579-5",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-089",
        aircraft: "525B CJ3, 525C CJ4",
        itemType: "Tool",
        name: "AIleron, Elevator & rudder trim freeplay fixture",
        partNumber: "CJMD827-002",
        manufacturer: "Cessna",
        reason: "Optional",
        stage: "Stage 3",
        unitPrice: "$18,248.81",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://www.airpowerinc.com/cjmd827-002?srsltid=AfmBOooHwU7e8jJl--45lTVrkvA2CkckRmFnuahrzSaVj5VQrr83dda7",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-090",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "anti-skid test set",
        partNumber: "99-791",
        manufacturer: "Hydro-Aire",
        reason: "Optional",
        stage: "Stage 3",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-091",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "anti-skid test set adapter cable",
        partNumber: "99-791-581",
        manufacturer: "Hydro-Aire",
        reason: "Optional",
        stage: "Stage 3",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-092",
        aircraft: "525 CJ1, 525A CJ2, 525B CJ3, 525C CJ4",
        itemType: "Tool",
        name: "Attenuator (30DB)",
        partNumber: "500-3000",
        manufacturer: "Artex aircraft supplies",
        reason: "Need For Advanced Troubleshooting",
        stage: "Stage 3",
        unitPrice: "$106.55",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://shop.boeing.com/aviation-supply/search?text=500-3000+Inline+30Db+Attenuator",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-093",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "check valve R&I tool",
        partNumber: "6286005-1",
        manufacturer: "Cessna",
        reason: "Needed for Repairs",
        stage: "Stage 3",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-094",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "control wheel leveling tool",
        partNumber: "CJMD8C27-003",
        manufacturer: "Cessna",
        reason: "Needed For Standard Inspections",
        stage: "Stage 3",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-095",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "dial indicator base wing refinsishing tool kit",
        partNumber: "CJMD820-001C",
        manufacturer: "Cessna",
        reason: "Needed For Standard Inspections",
        stage: "Stage 3",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Own Equivilent",
        notes: "Not needed, alternate on hand",
        received: false
    },
    {
        id: "PP-096",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "electric windshield anti-ice test box",
        partNumber: "CJMD756-100",
        manufacturer: "Cessna",
        reason: "Needed For Standard Inspections",
        stage: "Stage 3",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-097",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "EMT kit",
        partNumber: "9912691-1",
        manufacturer: "Cessna",
        reason: "Needed for Repairs",
        stage: "Stage 3",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-098",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "engine build up dolly",
        partNumber: "08-2021-0000 Also, order Adapter Kit K-2032",
        manufacturer: "Tronair",
        reason: "Needed for Repairs",
        stage: "Stage 3",
        unitPrice: "$10,378.00",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/08-2021-0000",
        requestId: "",
        status: "In Research",
        notes: "K-2032 is 5,376.00 l lead time",
        received: false
    },
    {
        id: "PP-099",
        aircraft: "525A CJ2, 525B CJ3, 525 CJ1, 525C CJ4",
        itemType: "Tool",
        name: "engine sling",
        partNumber: "08-0119-8000 (CJMD871-001)",
        manufacturer: "Tronair",
        reason: "Needed for Repairs",
        stage: "Stage 3",
        unitPrice: "$1,653.00",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/08-0119-8000",
        requestId: "",
        status: "In Research",
        notes: "lead time",
        received: false
    },
    {
        id: "PP-100",
        aircraft: "525C CJ4, 525 CJ1, 525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "engine sling",
        partNumber: "08-0147C4000 or 08-0119-8000",
        manufacturer: "Tronair",
        reason: "Needed for Repairs",
        stage: "Stage 3",
        unitPrice: "$1,706.00",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/08-0147C4000",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-101",
        aircraft: "525C CJ4, 525 CJ1, 525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "engine sling adapter",
        partNumber: "K-4375",
        manufacturer: "Tronair",
        reason: "Needed for Repairs",
        stage: "Stage 3",
        unitPrice: "$822.00",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/K-4375",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-102",
        aircraft: "525C CJ4, 525 CJ1, 525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "engine stand",
        partNumber: "08-2021C0000",
        manufacturer: "Tronair",
        reason: "Needed for Repairs",
        stage: "Stage 3",
        unitPrice: "$10,378.00",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/08-2021C0000",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-103",
        aircraft: "525C CJ4, 525 CJ1, 525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "engine stand adapter",
        partNumber: "K-4190",
        manufacturer: "Tronair",
        reason: "Needed for Repairs",
        stage: "Stage 3",
        unitPrice: "$6,178.00",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/K-4190",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-104",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "fuselage vane protractor",
        partNumber: "1939-6 (CJMD834-003)",
        manufacturer: "Safe Flight Instrument",
        reason: "Needed for Repairs",
        stage: "Stage 3",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-105",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "horizontal stabilizer assy lifting fixture",
        partNumber: "CJMD8C55-001",
        manufacturer: "Cessna",
        reason: "Needed for Repairs",
        stage: "Stage 3",
        unitPrice: "$34,567.93",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/CJMD8C55-001",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-106",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "hydraulic ground power unit",
        partNumber: "CJMD812-002",
        manufacturer: "Cessna",
        reason: "Needed For Standard Inspections",
        stage: "Stage 3",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Owned",
        notes: "Owned",
        received: false
    },
    {
        id: "PP-107",
        aircraft: "525A CJ2, 525B CJ3, 525C CJ4",
        itemType: "Tool",
        name: "main gear oleo tool",
        partNumber: "CJMD832-005",
        manufacturer: "Cessna",
        reason: "Optional",
        stage: "Stage 3",
        unitPrice: "$529.00",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://aeroval.com/ref/493208/CJMD832-005/",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-108",
        aircraft: "525A CJ2",
        itemType: "Tool",
        name: "pressurization cart",
        partNumber: "6388008-1 (CJMD821-001)",
        manufacturer: "Cessna",
        reason: "Needed For Standard Inspections",
        stage: "Stage 3",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Own Equivilent",
        notes: "Not needed, alternate on hand",
        received: false
    },
    {
        id: "PP-109",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "roll force tool",
        partNumber: "CJMD8C31-002",
        manufacturer: "Cessna",
        reason: "Needed For Standard Inspections",
        stage: "Stage 3",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-110",
        aircraft: "525B CJ3",
        itemType: "Tool",
        name: "Rubber/Seam Roller",
        partNumber: "75-5410-0401-8",
        manufacturer: "",
        reason: "Needed for Repairs",
        stage: "Stage 3",
        unitPrice: "$35.00",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-111",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "rudder bias torque adapter tool",
        partNumber: "CJMD8B27-002",
        manufacturer: "Cessna",
        reason: "Needed For Standard Inspections",
        stage: "Stage 3",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-112",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "rudder pedal force tool",
        partNumber: "CJMD8C31-003",
        manufacturer: "Cessna",
        reason: "Needed For Standard Inspections",
        stage: "Stage 3",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-113",
        aircraft: "525 CJ1, 525A CJ2, 525B CJ3, 525C CJ4",
        itemType: "Tool",
        name: "SARSAT Tester",
        partNumber: "455-9100",
        manufacturer: "Airtex Systems",
        reason: "Need For Advanced Troubleshooting",
        stage: "Stage 3",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-114",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "windshield bleed air anti-ice test tube",
        partNumber: "CJMD130-100",
        manufacturer: "Cessna",
        reason: "Needed for Repairs",
        stage: "Stage 3",
        unitPrice: "$533.00",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://aeroval.com/ref/493049/CJMD130-100/",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-115",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "wing light tool",
        partNumber: "CJMD8A33-001",
        manufacturer: "Cessna",
        reason: "Optional",
        stage: "Stage 3",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-116",
        aircraft: "525 CJ1, 525A CJ2, 525B CJ3, 525C CJ4",
        itemType: "Part",
        name: "hydraulic filter w/ oring",
        partNumber: "9912579-2",
        manufacturer: "",
        reason: "For Parts Stocking",
        stage: "Stage 4",
        unitPrice: "$909.99",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/9912579-2",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-117",
        aircraft: "525 CJ1, 525A CJ2",
        itemType: "Part",
        name: "main ship battery (28AMP Hour)",
        partNumber: "9914058-9",
        manufacturer: "Marathon",
        reason: "Optional",
        stage: "Stage 4",
        unitPrice: "$25,853.00",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/9914058-9",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-118",
        aircraft: "525 CJ1",
        itemType: "Part",
        name: "main ship battery (44 AMP Hour)",
        partNumber: "9914058-6",
        manufacturer: "Marathon",
        reason: "Optional",
        stage: "Stage 4",
        unitPrice: "$12,095.00",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/9914058-6",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-119",
        aircraft: "525 CJ1",
        itemType: "Part",
        name: "starter/generator",
        partNumber: "9912125-2 (alt. -3/-4)",
        manufacturer: "",
        reason: "Needed for Repairs",
        stage: "Stage 4",
        unitPrice: "$17,280.00",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/9912125-2",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-120",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "bleed air cap(block off) (FJ44-2C)",
        partNumber: "NK1008346-10",
        manufacturer: "Cessna",
        reason: "Needed for Repairs",
        stage: "Stage 4",
        unitPrice: "$1,022.34",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/NK1008346-10",
        requestId: "",
        status: "In Research",
        notes: "Waiting for vendors",
        received: false
    },
    {
        id: "PP-121",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "bleed air cap(block off) (FJ44-3A)",
        partNumber: "CJMD8B71-001",
        manufacturer: "Cessna",
        reason: "Needed for Repairs",
        stage: "Stage 4",
        unitPrice: "$2,677.25",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/CJMD8B71-001",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-122",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "engine bleed air cap",
        partNumber: "CJMD8C36-001",
        manufacturer: "Cessna",
        reason: "Optional",
        stage: "Stage 4",
        unitPrice: "$3,600.00",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://aeroval.com/ref/493322/CJMDS36-001/",
        requestId: "",
        status: "In Research",
        notes: "",
        received: false
    },
    {
        id: "PP-123",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "altitude encoder test set",
        partNumber: "2656-G",
        manufacturer: "Barfield Instrument",
        reason: "Needed For Standard Inspections",
        stage: "Stage 4",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-124",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "ARINC 429 PCMCIA card",
        partNumber: "CM429-1",
        manufacturer: "Ballard Technology",
        reason: "Optional",
        stage: "Stage 4",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-125",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "cabin door hinge inner eccentric wrench",
        partNumber: "CJMD8C52-004",
        manufacturer: "Cessna",
        reason: "Needed for Repairs",
        stage: "Stage 4",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-126",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "cabin door hitch outer eccentric wrench",
        partNumber: "CJMD8C52-003",
        manufacturer: "Cessna",
        reason: "Needed for Repairs",
        stage: "Stage 4",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-127",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "cabin door latch inner eccentric wrench",
        partNumber: "CJMD8C52-002",
        manufacturer: "Cessna",
        reason: "Needed for Repairs",
        stage: "Stage 4",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-128",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "cabin door latch outer eccentric wrench",
        partNumber: "CJMD8C52-001",
        manufacturer: "Cessna",
        reason: "Needed for Repairs",
        stage: "Stage 4",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-129",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "cabin door sight glass wrench",
        partNumber: "CJMD8C52-005",
        manufacturer: "Cessna",
        reason: "Needed for Repairs",
        stage: "Stage 4",
        unitPrice: "$8,821.22",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/CJMD8C52-005",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-130",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "calbration standard",
        partNumber: "CJMD156-101",
        manufacturer: "Cessna",
        reason: "Optional",
        stage: "Stage 4",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-131",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "camber adjustment tool",
        partNumber: "CJMD8C32-001",
        manufacturer: "Cessna",
        reason: "Needed for Repairs",
        stage: "Stage 4",
        unitPrice: "$6,643.00",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/CJMD8C32-001",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-132",
        aircraft: "525A CJ2, 525B CJ3, 525C CJ4",
        itemType: "Tool",
        name: "control surface balance fixture kit",
        partNumber: "5180002-1",
        manufacturer: "Cessna",
        reason: "Needed for Repairs",
        stage: "Stage 4",
        unitPrice: "$1,171.00",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://aeroval.com/ref/995749/5180002-1/",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-133",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "DCU rigging harness",
        partNumber: "8788019-1",
        manufacturer: "Cessna",
        reason: "Needed for Repairs",
        stage: "Stage 4",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-134",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "elevator streamline fixture",
        partNumber: "CJMD8C27-002",
        manufacturer: "Cessna",
        reason: "Needed For Standard Inspections",
        stage: "Stage 4",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-135",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "elliptical wing refinsihing tool kit",
        partNumber: "CJMD820-001B",
        manufacturer: "Cessna",
        reason: "Optional",
        stage: "Stage 4",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-136",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "engine lift adapter",
        partNumber: "K-2012",
        manufacturer: "Tronair",
        reason: "Needed for Repairs",
        stage: "Stage 4",
        unitPrice: "$9,966.00",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/K-2012",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-137",
        aircraft: "525A CJ2",
        itemType: "Tool",
        name: "left elevator rig boards",
        partNumber: "OF49-01483 (CJMD8A27-003)",
        manufacturer: "Cessna",
        reason: "Needed For Standard Inspections",
        stage: "Stage 4",
        unitPrice: "$9,045.74",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://www.airpowerinc.com/cjmd8a27-004",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-138",
        aircraft: "525A CJ2, 525B CJ3, 525C CJ4",
        itemType: "Tool",
        name: "main gear oleo tool kit",
        partNumber: "CJMD832-001",
        manufacturer: "Cessna",
        reason: "Needed for Repairs",
        stage: "Stage 4",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-139",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "main gear trunnion pin bore go gauge",
        partNumber: "CJMD832-007",
        manufacturer: "Cessna",
        reason: "Needed for Repairs",
        stage: "Stage 4",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-140",
        aircraft: "525A CJ2",
        itemType: "Tool",
        name: "main landing gear trunnion bearing removal",
        partNumber: "CJMD832-006",
        manufacturer: "Cessna",
        reason: "Needed for Repairs",
        stage: "Stage 4",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-141",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "PCB breakout box",
        partNumber: "PCB60M",
        manufacturer: "Cessna",
        reason: "Need For Advanced Troubleshooting",
        stage: "Stage 4",
        unitPrice: "$2,680.00",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://aeroval.com/ref/514810/PCB60/",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-142",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "pitch force tool",
        partNumber: "CJMD8C31-001",
        manufacturer: "Cessna",
        reason: "Needed For Standard Inspections",
        stage: "Stage 4",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-143",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "right elevator rig boards",
        partNumber: "OF49-01483 (CJMD8A27-004)",
        manufacturer: "Cessna",
        reason: "Needed For Standard Inspections",
        stage: "Stage 4",
        unitPrice: "$9,045.74",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://www.airpowerinc.com/cjmd8a27-004",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-144",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "rudder check fixture",
        partNumber: "CJMD8C27-001",
        manufacturer: "Cessna",
        reason: "Needed For Standard Inspections",
        stage: "Stage 4",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-145",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "static port adapter",
        partNumber: "33410SM-125-4",
        manufacturer: "Nav-Aids",
        reason: "Needed For Standard Inspections",
        stage: "Stage 4",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-146",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "throttle switch test box",
        partNumber: "6588002-1",
        manufacturer: "Cessna",
        reason: "Optional",
        stage: "Stage 4",
        unitPrice: "$3,241.00",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://aeroval.com/ref/446055/6588002-1/",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-147",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "Thruline RF wattmeter",
        partNumber: "Model 43",
        manufacturer: "Bird Electronic",
        reason: "Need For Advanced Troubleshooting",
        stage: "Stage 4",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-148",
        aircraft: "525A CJ2, 525B CJ3",
        itemType: "Tool",
        name: "thrust attenuator rig tool",
        partNumber: "CJMD8A78-001",
        manufacturer: "Cessna",
        reason: "Optional",
        stage: "Stage 4",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-149",
        aircraft: "525C CJ4",
        itemType: "Tool",
        name: "underwater locator beacon (ULB) test set",
        partNumber: "Dukane Model 42A12",
        manufacturer: "Cessna",
        reason: "Needed For Standard Inspections",
        stage: "Stage 4",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-150",
        aircraft: "525 CJ1, 525A CJ2, 525B CJ3, 525C CJ4",
        itemType: "Part",
        name: "hydraulic filter Assembly",
        partNumber: "9912579-1",
        manufacturer: "",
        reason: "For Parts Stocking",
        stage: "Stage 5",
        unitPrice: "$4,083.00",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "https://ww2.txtav.com/Parts/PartSearch/PartsDetail/9912579-1",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-151",
        aircraft: "525B CJ3",
        itemType: "Tool",
        name: "Helium Leak Detector",
        partNumber: "ASM 310",
        manufacturer: "Alcatel vaccum products",
        reason: "Need For Advanced Troubleshooting",
        stage: "Stage 5",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-152",
        aircraft: "525A CJ2, 525B CJ3, 525C CJ4",
        itemType: "Tool",
        name: "lighting diverter strip locting tool",
        partNumber: "CJMD853-001",
        manufacturer: "Cessna",
        reason: "Optional",
        stage: "Stage 5",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-153",
        aircraft: "525A CJ2, 525B CJ3, 525C CJ4",
        itemType: "Tool",
        name: "main gear camber adjustment tool",
        partNumber: "CJMD8A32-001",
        manufacturer: "Cessna",
        reason: "Needed for Repairs",
        stage: "Stage 5",
        unitPrice: "",
        quantity: "",
        totalPrice: "$0.00",
        sourcingLink: "",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    },
    {
        id: "PP-154",
        aircraft: "525 CJ1, 525A CJ2, 525B CJ3, 525C CJ4, 560 Citation V, 560 Encore, 560 Encore+, 560 Ultra, 560XL Excel, 560XL-XLS, Citation 650, Citation 550, Citation 700, Citation X+, Citation X, 560XL-XLS+, Citation 500/501",
        itemType: "Tool",
        name: "Grease Lubrication Kit",
        partNumber: "ACK-2",
        manufacturer: "Macnaught",
        reason: "Needed For Standard Inspections",
        stage: "MRO Tooling Wishlist",
        unitPrice: "$550.00",
        quantity: "1",
        totalPrice: "$550.00",
        sourcingLink: "https://www.macnaughtusa.com/products/aviation-lube-kit-pn-ack2-02?utm_source=google&utm_medium=cpc&utm_campaign=FH-Aviation-Lube-Kit-EPM&utm_term=ACK-2&utm_term=aviation%20lube%20kit&utm_campaign=FH-Aviation-Lube-Kit-EPM&utm_source=adwords&utm_medium=ppc&hsa_acc=7379054809&hsa_cam=22871813752&hsa_grp=182234283303&hsa_ad=767942848533&hsa_src=g&hsa_tgt=kwd-2440181785361&hsa_kw=aviation%20lube%20kit&hsa_mt=p&hsa_net=adwords&hsa_ver=3&gad_source=1&gad_campaignid=22871813752&gbraid=0AAAAADEWd6_sUZHNP6xNFSTXNYBR_tK5g&gclid=Cj0KCQiArOvIBhDLARIsAPwJXObO3bE2QUJlm-jCJP4VM2qoMvSXjfZCYGA0NQKD50wrcNYyWktt6FcaAkEVEALw_wcB",
        requestId: "",
        status: "",
        notes: "",
        received: false
    },
    {
        id: "PP-158",
        aircraft: "525B CJ3",
        itemType: "Consumable",
        name: "Benzalkonium Choloride",
        partNumber: "APN 00-2572",
        manufacturer: "Safran Oxygen systems. (Formerly Avox)",
        reason: "Optional",
        stage: "",
        unitPrice: "$250.80",
        quantity: "",
        totalPrice: "",
        sourcingLink: "https://www.spectrumchemical.com/benzalkonium-chloride-solution-50-percent-nf-b1068?srsltid=AfmBOooaQowaavbHwc1QhY0LDSKlBe50HYdah8YfmH1zqXJbczIcIwgJ",
        requestId: "",
        status: "Sourcing",
        notes: "",
        received: false
    }
];